/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Room.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.76, 3.378]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.615}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['wood.009']} position={[-0.294, 0, 0]}>
          <mesh geometry={nodes.BezierCurve002.geometry} material={materials['metalic.007']} position={[0, 0.267, 0.053]} rotation={[Math.PI, 0, -Math.PI / 2]} />
        </mesh>
        <mesh geometry={nodes.Cube011.geometry} material={materials['wood.009']} position={[-0.001, 0.116, 0.115]}>
          <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['pot-1.007']} position={[-0.096, 0.008, -0.004]}>
            <mesh geometry={nodes.Circle.geometry} material={materials['stones.007']} position={[0, 0.064, 0]}>
              <mesh geometry={nodes.Plane012_2.geometry} material={materials['succulent-1.007']} position={[0, 0.006, 0]} />
              <mesh geometry={nodes.Plane015_1.geometry} material={materials['succulent-1.007']} position={[0, 0.012, 0]} rotation={[0, 0.89, 0]} />
              <mesh geometry={nodes.Plane016_2.geometry} material={materials['succulent-1.007']} position={[-0.003, 0.031, 0]} rotation={[-Math.PI, 1.403, -Math.PI]} />
              <mesh geometry={nodes.Plane017_2.geometry} material={materials['succulent-1.007']} position={[0, 0.015, 0]} />
              <mesh geometry={nodes.Plane018.geometry} material={materials['succulent-1.007']} position={[-0.001, 0.033, 0.002]} rotation={[Math.PI, -1.259, Math.PI]} />
            </mesh>
            <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['succulent-1.007']} position={[-0.003, 0.095, 0]} />
          </mesh>
          <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['pot-2.007']} position={[-0.196, 0.028, 0.022]}>
            <mesh geometry={nodes.BezierCurve.geometry} material={materials['succulent-2.007']} position={[-0.001, -0.018, -0.005]}>
              <mesh geometry={nodes.Cube014_3.geometry} material={materials['leaf 02.007']} position={[-0.001, 0.048, 0.04]} rotation={[-2.11, -1.002, 1.913]} scale={0.429} />
              <mesh geometry={nodes.Cube014_4.geometry} material={materials['leaf 02.007']} position={[0.008, 0.018, 0.007]} rotation={[-3.025, -0.112, -1.109]} scale={0.429} />
              <mesh geometry={nodes.Cube014_5.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.018, 0.002]} rotation={[-0.865, 0.088, 1.92]} scale={0.429} />
              <mesh geometry={nodes.Cube014_6.geometry} material={materials['leaf 02.007']} position={[-0.002, 0.019, 0.005]} rotation={[2.796, -0.697, -3.001]} scale={0.429} />
              <mesh geometry={nodes.Cube014_7.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.021, 0.004]} rotation={[-0.798, -0.317, 0.49]} scale={0.429} />
              <mesh geometry={nodes.Cube014_8.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.023, 0.003]} rotation={[0.371, -1.188, 0.512]} scale={0.429} />
              <mesh geometry={nodes.Cube014_9.geometry} material={materials['leaf 02.007']} position={[-0.006, 0.025, 0.004]} rotation={[-2.528, -0.586, 2.489]} scale={0.429} />
              <mesh geometry={nodes.Cube014_10.geometry} material={materials['leaf 02.007']} position={[-0.008, 0.025, 0.006]} rotation={[-0.504, 0.084, 1.408]} scale={0.429} />
              <mesh geometry={nodes.Cube014_11.geometry} material={materials['leaf 02.007']} position={[-0.01, 0.027, 0.006]} rotation={[-2.791, -1.019, 2.217]} scale={0.429} />
              <mesh geometry={nodes.Cube014_12.geometry} material={materials['leaf 02.007']} position={[-0.008, 0.025, 0.004]} rotation={[0.766, -0.689, 0.762]} scale={0.429} />
              <mesh geometry={nodes.Cube014_13.geometry} material={materials['leaf 02.007']} position={[-0.012, 0.027, 0.009]} rotation={[-0.904, 0.07, 1.794]} scale={0.429} />
              <mesh geometry={nodes.Cube014_14.geometry} material={materials['leaf 02.007']} position={[-0.014, 0.029, 0.009]} rotation={[-2.788, -1.073, 2.167]} scale={0.429} />
              <mesh geometry={nodes.Cube014_15.geometry} material={materials['leaf 02.007']} position={[-0.013, 0.027, 0.007]} rotation={[0.824, -0.618, 0.774]} scale={0.429} />
              <mesh geometry={nodes.Cube014_16.geometry} material={materials['leaf 02.007']} position={[-0.017, 0.029, 0.012]} rotation={[-0.869, 0.069, 1.845]} scale={0.429} />
              <mesh geometry={nodes.Cube014_17.geometry} material={materials['leaf 02.007']} position={[-0.019, 0.031, 0.013]} rotation={[-2.779, -1.121, 2.137]} scale={0.429} />
              <mesh geometry={nodes.Cube014_18.geometry} material={materials['leaf 02.007']} position={[-0.017, 0.029, 0.01]} rotation={[0.857, -0.567, 0.765]} scale={0.429} />
              <mesh geometry={nodes.Cube014_19.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.03, 0.016]} rotation={[-0.838, 0.075, 1.892]} scale={0.429} />
              <mesh geometry={nodes.Cube014_20.geometry} material={materials['leaf 02.007']} position={[-0.024, 0.033, 0.017]} rotation={[-2.112, -0.86, 2.416]} scale={0.429} />
              <mesh geometry={nodes.Cube014_21.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.031, 0.014]} rotation={[1.263, -0.852, 0.714]} scale={0.429} />
              <mesh geometry={nodes.Cube014_22.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.032, 0.019]} rotation={[-0.37, 0.172, 1.597]} scale={0.429} />
              <mesh geometry={nodes.Cube014_23.geometry} material={materials['leaf 02.007']} position={[-0.028, 0.034, 0.021]} rotation={[-1.663, -0.547, 2.451]} scale={0.429} />
              <mesh geometry={nodes.Cube014_24.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.033, 0.018]} rotation={[1.81, -1.148, 0.853]} scale={0.429} />
              <mesh geometry={nodes.Cube014_25.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.032, 0.019]} rotation={[0.072, 0.104, 1.251]} scale={0.429} />
              <mesh geometry={nodes.Cube014_26.geometry} material={materials['leaf 02.007']} position={[-0.033, 0.034, 0.026]} rotation={[-1.279, -0.231, 2.361]} scale={0.429} />
              <mesh geometry={nodes.Cube014_27.geometry} material={materials['leaf 02.007']} position={[-0.031, 0.035, 0.022]} rotation={[3.064, -1.318, 1.735]} scale={0.429} />
              <mesh geometry={nodes.Cube014_28.geometry} material={materials['leaf 02.007']} position={[-0.032, 0.034, 0.022]} rotation={[0.832, -0.341, 0.744]} scale={0.429} />
              <mesh geometry={nodes.Cube014_29.geometry} material={materials['leaf 02.007']} position={[-0.038, 0.035, 0.031]} rotation={[-0.891, 0.052, 2.164]} scale={0.429} />
              <mesh geometry={nodes.Cube014_30.geometry} material={materials['leaf 02.007']} position={[-0.035, 0.036, 0.028]} rotation={[-1.666, -0.722, 2.574]} scale={0.429} />
              <mesh geometry={nodes.Cube014_31.geometry} material={materials['leaf 02.007']} position={[-0.037, 0.035, 0.027]} rotation={[1.151, -0.65, 0.576]} scale={0.429} />
              <mesh geometry={nodes.Cube014_32.geometry} material={materials['leaf 02.007']} position={[-0.039, 0.035, 0.03]} rotation={[-0.031, 0.232, 1.422]} scale={0.429} />
              <mesh geometry={nodes.Cube014_33.geometry} material={materials['leaf 02.007']} position={[-0.04, 0.036, 0.033]} rotation={[-1.315, -0.361, 2.509]} scale={0.429} />
              <mesh geometry={nodes.Cube014_34.geometry} material={materials['leaf 02.007']} position={[-0.041, 0.037, 0.032]} rotation={[2.239, -1.366, 0.936]} scale={0.429} />
              <mesh geometry={nodes.Cube014_35.geometry} material={materials['leaf 02.007']} position={[-0.043, 0.036, 0.035]} rotation={[0.41, 0.14, 1.05]} scale={0.429} />
              <mesh geometry={nodes.Cube014_36.geometry} material={materials['leaf 02.007']} position={[-0.044, 0.036, 0.038]} rotation={[-0.614, 0.245, 2.015]} scale={0.429} />
              <mesh geometry={nodes.Cube014_37.geometry} material={materials['leaf 02.007']} position={[-0.045, 0.038, 0.038]} rotation={[-1.975, -1.275, 2.675]} scale={0.429} />
              <mesh geometry={nodes.Cube014_38.geometry} material={materials['leaf 02.007']} position={[-0.048, 0.037, 0.04]} rotation={[1.047, -0.423, 0.5]} scale={0.429} />
              <mesh geometry={nodes.Cube014_39.geometry} material={materials['leaf 02.007']} position={[-0.049, 0.036, 0.043]} rotation={[-0.144, 0.408, 1.619]} scale={0.429} />
              <mesh geometry={nodes.Cube014_40.geometry} material={materials['leaf 02.007']} position={[-0.048, 0.038, 0.044]} rotation={[-1.282, -0.457, 2.693]} scale={0.429} />
              <mesh geometry={nodes.Cube014_41.geometry} material={materials['leaf 02.007']} position={[-0.052, 0.038, 0.045]} rotation={[1.262, -0.787, 0.285]} scale={0.429} />
              <mesh geometry={nodes.Cube014_42.geometry} material={materials['leaf 02.007']} position={[-0.05, 0.037, 0.042]} rotation={[0.698, 0.08, 0.806]} scale={0.429} />
              <mesh geometry={nodes.Cube014_43.geometry} material={materials['leaf 02.007']} position={[-0.052, 0.038, 0.05]} rotation={[-1.006, -0.051, 2.543]} scale={0.429} />
              <mesh geometry={nodes.Cube014_44.geometry} material={materials['leaf 02.007']} position={[-0.054, 0.039, 0.052]} rotation={[-1.385, -1.488, -2.959]} scale={0.429} />
              <mesh geometry={nodes.Cube014_45.geometry} material={materials['leaf 02.007']} position={[-0.054, 0.038, 0.048]} rotation={[0.987, -0.217, 0.498]} scale={0.429} />
              <mesh geometry={nodes.Cube014_46.geometry} material={materials['leaf 02.007']} position={[-0.056, 0.037, 0.055]} rotation={[-0.251, 0.529, 1.817]} scale={0.429} />
              <mesh geometry={nodes.Cube014_47.geometry} material={materials['leaf 02.007']} position={[-0.057, 0.039, 0.058]} rotation={[-1.277, -1.039, -3.128]} scale={0.429} />
              <mesh geometry={nodes.Cube014_48.geometry} material={materials['leaf 02.007']} position={[-0.056, 0.039, 0.054]} rotation={[1.217, -1.02, -0.02]} scale={0.429} />
              <mesh geometry={nodes.Cube014_49.geometry} material={materials['leaf 02.007']} position={[-0.057, 0.037, 0.055]} rotation={[0.67, 0.289, 0.822]} scale={0.429} />
              <mesh geometry={nodes.Cube014_50.geometry} material={materials['leaf 02.007']} position={[-0.06, 0.039, 0.062]} rotation={[1.2, -0.609, -0.068]} scale={0.429} />
              <mesh geometry={nodes.Cube014_51.geometry} material={materials['leaf 02.007']} position={[-0.059, 0.038, 0.063]} rotation={[-0.813, -0.715, -2.944]} scale={0.429} />
              <mesh geometry={nodes.Cube014_52.geometry} material={materials['leaf 02.007']} position={[-0.059, 0.036, 0.066]} rotation={[-0.512, 0.528, 2.625]} scale={0.429} />
              <mesh geometry={nodes.Cube014_53.geometry} material={materials['leaf 02.007']} position={[-0.061, 0.036, 0.067]} rotation={[1.235, 0.389, 0.353]} scale={0.429} />
              <mesh geometry={nodes.Cube014_54.geometry} material={materials['leaf 02.007']} position={[-0.059, 0.036, 0.069]} rotation={[-0.476, -0.609, -2.727]} scale={0.429} />
              <mesh geometry={nodes.Cube014_55.geometry} material={materials['leaf 02.007']} position={[-0.059, 0.034, 0.072]} rotation={[-0.047, 0.969, 2.184]} scale={0.429} />
              <mesh geometry={nodes.Cube014_56.geometry} material={materials['leaf 02.007']} position={[-0.06, 0.034, 0.074]} rotation={[1.412, -0.388, -0.37]} scale={0.429} />
              <mesh geometry={nodes.Cube014_57.geometry} material={materials['leaf 02.007']} position={[-0.059, 0.033, 0.075]} rotation={[-0.474, -0.114, -2.966]} scale={0.429} />
              <mesh geometry={nodes.Cube014_58.geometry} material={materials['leaf 02.007']} position={[-0.06, 0.032, 0.075]} rotation={[1.39, 0.757, 0.443]} scale={0.429} />
              <mesh geometry={nodes.Cube014_59.geometry} material={materials['leaf 02.007']} position={[-0.059, 0.03, 0.081]} rotation={[1.184, -0.704, -0.883]} scale={0.429} />
              <mesh geometry={nodes.Cube014_60.geometry} material={materials['leaf 02.007']} position={[-0.058, 0.028, 0.082]} rotation={[-0.427, 0.388, 3.112]} scale={0.429} />
              <mesh geometry={nodes.Cube014_61.geometry} material={materials['leaf 02.007']} position={[-0.058, 0.028, 0.082]} rotation={[1.055, 1.151, 1.045]} scale={0.429} />
              <mesh geometry={nodes.Cube014_62.geometry} material={materials['leaf 02.007']} position={[-0.058, 0.025, 0.086]} rotation={[1.726, 0.552, 0.033]} scale={0.429} />
              <mesh geometry={nodes.Cube014_63.geometry} material={materials['leaf 02.007']} position={[-0.057, 0.024, 0.088]} rotation={[1.383, -0.496, -0.84]} scale={0.429} />
              <mesh geometry={nodes.Cube014_64.geometry} material={materials['leaf 02.007']} position={[-0.056, 0.022, 0.09]} rotation={[1.796, -0.004, -0.486]} scale={0.429} />
              <mesh geometry={nodes.Cube014_65.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.019, 0.002]} rotation={[-1.744, 0.221, 1.112]} scale={0.429} />
              <mesh geometry={nodes.Cube014_66.geometry} material={materials['leaf 02.007']} position={[0, 0.018, 0.002]} rotation={[2.836, -0.405, 2.6]} scale={0.429} />
              <mesh geometry={nodes.Cube014_67.geometry} material={materials['leaf 02.007']} position={[-0.002, 0.017, 0.003]} rotation={[-1.044, -0.531, 0.475]} scale={0.429} />
              <mesh geometry={nodes.Cube014_68.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.022, 0]} rotation={[-3.01, 0.037, 2.32]} scale={0.429} />
              <mesh geometry={nodes.Cube014_69.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.02, 0]} rotation={[-0.92, -0.612, 0.457]} scale={0.429} />
              <mesh geometry={nodes.Cube014_70.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.023, -0.002]} rotation={[2.875, -0.597, 2.653]} scale={0.429} />
              <mesh geometry={nodes.Cube014_71.geometry} material={materials['leaf 02.007']} position={[-0.008, 0.026, -0.002]} rotation={[-2.516, 0.189, 2.065]} scale={0.429} />
              <mesh geometry={nodes.Cube014_72.geometry} material={materials['leaf 02.007']} position={[-0.009, 0.026, -0.002]} rotation={[-1.727, 0.248, 1.467]} scale={0.429} />
              <mesh geometry={nodes.Cube014_73.geometry} material={materials['leaf 02.007']} position={[-0.01, 0.028, -0.003]} rotation={[-2.243, 0.048, 1.967]} scale={0.429} />
              <mesh geometry={nodes.Cube014_74.geometry} material={materials['leaf 02.007']} position={[-0.012, 0.03, -0.004]} rotation={[3.107, -0.666, 2.204]} scale={0.429} />
              <mesh geometry={nodes.Cube014_75.geometry} material={materials['leaf 02.007']} position={[-0.013, 0.03, -0.004]} rotation={[2.293, -0.919, 1.966]} scale={0.429} />
              <mesh geometry={nodes.Cube014_76.geometry} material={materials['leaf 02.007']} position={[-0.015, 0.031, -0.004]} rotation={[2.634, -0.673, 2.008]} scale={0.429} />
              <mesh geometry={nodes.Cube014_77.geometry} material={materials['leaf 02.007']} position={[-0.019, 0.032, -0.004]} rotation={[-2.529, -0.219, 1.65]} scale={0.429} />
              <mesh geometry={nodes.Cube014_78.geometry} material={materials['leaf 02.007']} position={[-0.018, 0.03, -0.004]} rotation={[-0.371, -0.692, 1.166]} scale={0.429} />
              <mesh geometry={nodes.Cube014_79.geometry} material={materials['leaf 02.007']} position={[-0.02, 0.033, -0.005]} rotation={[3.008, -0.316, 1.908]} scale={0.429} />
              <mesh geometry={nodes.Cube014_80.geometry} material={materials['leaf 02.007']} position={[-0.023, 0.031, -0.005]} rotation={[-0.752, -0.654, 1.1]} scale={0.429} />
              <mesh geometry={nodes.Cube014_81.geometry} material={materials['leaf 02.007']} position={[-0.024, 0.033, -0.006]} rotation={[-2.736, -0.13, 1.651]} scale={0.429} />
              <mesh geometry={nodes.Cube014_82.geometry} material={materials['leaf 02.007']} position={[-0.024, 0.032, -0.007]} rotation={[1.558, -0.849, 2.002]} scale={0.429} />
              <mesh geometry={nodes.Cube014_83.geometry} material={materials['leaf 02.007']} position={[-0.03, 0.034, -0.007]} rotation={[-1.719, -0.292, 1.14]} scale={0.429} />
              <mesh geometry={nodes.Cube014_84.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.034, -0.009]} rotation={[1.765, -0.812, 2.107]} scale={0.429} />
              <mesh geometry={nodes.Cube014_85.geometry} material={materials['leaf 02.007']} position={[-0.031, 0.034, -0.008]} rotation={[-1.127, -0.562, 0.996]} scale={0.429} />
              <mesh geometry={nodes.Cube014_86.geometry} material={materials['leaf 02.007']} position={[-0.035, 0.035, -0.01]} rotation={[-1.704, -0.259, 1.146]} scale={0.429} />
              <mesh geometry={nodes.Cube014_87.geometry} material={materials['leaf 02.007']} position={[-0.036, 0.036, -0.01]} rotation={[-1.857, -0.202, 1.208]} scale={0.429} />
              <mesh geometry={nodes.Cube014_88.geometry} material={materials['leaf 02.007']} position={[-0.038, 0.037, -0.011]} rotation={[-1.983, -0.167, 1.255]} scale={0.429} />
              <mesh geometry={nodes.Cube014_89.geometry} material={materials['leaf 02.007']} position={[-0.04, 0.037, -0.012]} rotation={[-2.155, -0.127, 1.313]} scale={0.429} />
              <mesh geometry={nodes.Cube014_90.geometry} material={materials['leaf 02.007']} position={[-0.041, 0.037, -0.013]} rotation={[-1.887, -0.231, 1.176]} scale={0.429} />
              <mesh geometry={nodes.Cube014_91.geometry} material={materials['leaf 02.007']} position={[-0.043, 0.038, -0.014]} rotation={[-2.457, -0.089, 1.421]} scale={0.429} />
              <mesh geometry={nodes.Cube014_92.geometry} material={materials['leaf 02.007']} position={[-0.044, 0.039, -0.016]} rotation={[2.761, -0.203, 1.922]} scale={0.429} />
              <mesh geometry={nodes.Cube014_93.geometry} material={materials['leaf 02.007']} position={[-0.045, 0.038, -0.017]} rotation={[1.742, -0.672, 2.178]} scale={0.429} />
              <mesh geometry={nodes.Cube014_94.geometry} material={materials['leaf 02.007']} position={[-0.048, 0.038, -0.016]} rotation={[-1.904, -0.78, 0.93]} scale={0.429} />
              <mesh geometry={nodes.Cube014_95.geometry} material={materials['leaf 02.007']} position={[-0.051, 0.037, -0.018]} rotation={[-3.066, -0.274, 0.893]} scale={0.429} />
              <mesh geometry={nodes.Cube014_96.geometry} material={materials['leaf 02.007']} position={[-0.052, 0.037, -0.018]} rotation={[3.004, -0.241, 0.892]} scale={0.429} />
              <mesh geometry={nodes.Cube014_97.geometry} material={materials['leaf 02.007']} position={[-0.053, 0.035, -0.019]} rotation={[2.467, 0.06, 1.121]} scale={0.429} />
              <mesh geometry={nodes.Cube014_98.geometry} material={materials['leaf 02.007']} position={[-0.056, 0.033, -0.02]} rotation={[2.274, 0.163, 1.157]} scale={0.429} />
              <mesh geometry={nodes.Cube014_99.geometry} material={materials['leaf 02.007']} position={[-0.056, 0.031, -0.021]} rotation={[1.66, 0.265, 1.66]} scale={0.429} />
              <mesh geometry={nodes.Cube014_100.geometry} material={materials['leaf 02.007']} position={[-0.058, 0.029, -0.02]} rotation={[0.485, -0.524, 2.598]} scale={0.429} />
              <mesh geometry={nodes.Cube014_101.geometry} material={materials['leaf 02.007']} position={[-0.062, 0.025, -0.021]} rotation={[2.159, 0.312, 0.913]} scale={0.429} />
              <mesh geometry={nodes.Cube014_102.geometry} material={materials['leaf 02.007']} position={[-0.062, 0.022, -0.02]} rotation={[0.31, -0.57, 3.069]} scale={0.429} />
              <mesh geometry={nodes.Cube014_103.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.018, 0.001]} rotation={[-2.753, -1.35, -1.924]} scale={0.429} />
              <mesh geometry={nodes.Cube014_104.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.022, -0.001]} rotation={[2.913, 0.092, 2.545]} scale={0.429} />
              <mesh geometry={nodes.Cube014_105.geometry} material={materials['leaf 02.007']} position={[-0.007, 0.022, -0.001]} rotation={[-1.553, -0.028, 0.532]} scale={0.429} />
              <mesh geometry={nodes.Cube014_106.geometry} material={materials['leaf 02.007']} position={[-0.006, 0.021, -0.003]} rotation={[3.011, -1.433, -2.384]} scale={0.429} />
              <mesh geometry={nodes.Cube014_107.geometry} material={materials['leaf 02.007']} position={[-0.008, 0.025, -0.005]} rotation={[2.857, 0.06, 2.457]} scale={0.429} />
              <mesh geometry={nodes.Cube014_108.geometry} material={materials['leaf 02.007']} position={[-0.01, 0.025, -0.006]} rotation={[-1.594, -0.099, 0.588]} scale={0.429} />
              <mesh geometry={nodes.Cube014_109.geometry} material={materials['leaf 02.007']} position={[-0.009, 0.024, -0.007]} rotation={[2.269, -1.453, -3.088]} scale={0.429} />
              <mesh geometry={nodes.Cube014_110.geometry} material={materials['leaf 02.007']} position={[-0.011, 0.028, -0.01]} rotation={[2.838, 0.023, 2.395]} scale={0.429} />
              <mesh geometry={nodes.Cube014_111.geometry} material={materials['leaf 02.007']} position={[-0.013, 0.028, -0.01]} rotation={[-1.593, -0.144, 0.646]} scale={0.429} />
              <mesh geometry={nodes.Cube014_112.geometry} material={materials['leaf 02.007']} position={[-0.012, 0.027, -0.011]} rotation={[1.692, -1.439, 2.619]} scale={0.429} />
              <mesh geometry={nodes.Cube014_113.geometry} material={materials['leaf 02.007']} position={[-0.014, 0.03, -0.014]} rotation={[2.851, -0.025, 2.356]} scale={0.429} />
              <mesh geometry={nodes.Cube014_114.geometry} material={materials['leaf 02.007']} position={[-0.017, 0.03, -0.014]} rotation={[-1.553, -0.163, 0.711]} scale={0.429} />
              <mesh geometry={nodes.Cube014_115.geometry} material={materials['leaf 02.007']} position={[-0.016, 0.03, -0.015]} rotation={[1.269, -1.417, 2.162]} scale={0.429} />
              <mesh geometry={nodes.Cube014_116.geometry} material={materials['leaf 02.007']} position={[-0.018, 0.033, -0.018]} rotation={[2.897, -0.091, 2.34]} scale={0.429} />
              <mesh geometry={nodes.Cube014_117.geometry} material={materials['leaf 02.007']} position={[-0.021, 0.033, -0.017]} rotation={[-1.475, -0.15, 0.789]} scale={0.429} />
              <mesh geometry={nodes.Cube014_118.geometry} material={materials['leaf 02.007']} position={[-0.02, 0.032, -0.019]} rotation={[0.886, -1.388, 1.705]} scale={0.429} />
              <mesh geometry={nodes.Cube014_119.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.036, -0.021]} rotation={[2.99, -0.178, 2.354]} scale={0.429} />
              <mesh geometry={nodes.Cube014_120.geometry} material={materials['leaf 02.007']} position={[-0.024, 0.036, -0.02]} rotation={[-1.786, 0.145, 1.106]} scale={0.429} />
              <mesh geometry={nodes.Cube014_121.geometry} material={materials['leaf 02.007']} position={[-0.024, 0.035, -0.021]} rotation={[-0.903, -0.697, 0.532]} scale={0.429} />
              <mesh geometry={nodes.Cube014_122.geometry} material={materials['leaf 02.007']} position={[-0.026, 0.037, -0.024]} rotation={[-0.108, -1.444, 0.929]} scale={0.429} />
              <mesh geometry={nodes.Cube014_123.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.038, -0.025]} rotation={[2.316, -1.299, -3.032]} scale={0.429} />
              <mesh geometry={nodes.Cube014_124.geometry} material={materials['leaf 02.007']} position={[-0.028, 0.039, -0.026]} rotation={[2.616, -1.252, -2.455]} scale={0.429} />
              <mesh geometry={nodes.Cube014_125.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.039, -0.029]} rotation={[-2.395, -1.056, -0.671]} scale={0.429} />
              <mesh geometry={nodes.Cube014_126.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.039, -0.03]} rotation={[3.102, -1.074, -1.477]} scale={0.429} />
              <mesh geometry={nodes.Cube014_127.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.038, -0.033]} rotation={[3.133, -0.967, -1.243]} scale={0.429} />
              <mesh geometry={nodes.Cube014_128.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.037, -0.037]} rotation={[-3.107, -0.855, -0.964]} scale={0.429} />
              <mesh geometry={nodes.Cube014_129.geometry} material={materials['leaf 02.007']} position={[-0.028, 0.036, -0.038]} rotation={[2.019, -0.775, -2.271]} scale={0.429} />
              <mesh geometry={nodes.Cube014_130.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.034, -0.041]} rotation={[1.654, -0.53, -2.621]} scale={0.429} />
              <mesh geometry={nodes.Cube014_131.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.03, -0.046]} rotation={[1.433, -0.285, -2.847]} scale={0.429} />
              <mesh geometry={nodes.Cube014_132.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.029, -0.047]} rotation={[1.31, 0.414, 2.94]} scale={0.429} />
              <mesh geometry={nodes.Cube014_133.geometry} material={materials['leaf 02.007']} position={[-0.002, 0.017, 0]} rotation={[-1.016, -0.283, -0.092]} scale={0.429} />
              <mesh geometry={nodes.Cube014_134.geometry} material={materials['leaf 02.007']} position={[-0.001, 0.02, -0.001]} rotation={[-2.409, 0.952, 1.327]} scale={0.429} />
              <mesh geometry={nodes.Cube014_135.geometry} material={materials['leaf 02.007']} position={[-0.001, 0.021, -0.002]} rotation={[-2.761, 0.94, 1.636]} scale={0.429} />
              <mesh geometry={nodes.Cube014_136.geometry} material={materials['leaf 02.007']} position={[-0.001, 0.022, -0.004]} rotation={[-2.956, 0.903, 1.872]} scale={0.429} />
              <mesh geometry={nodes.Cube014_137.geometry} material={materials['leaf 02.007']} position={[-0.001, 0.022, -0.007]} rotation={[2.712, 0.046, 2.985]} scale={0.429} />
              <mesh geometry={nodes.Cube014_138.geometry} material={materials['leaf 02.007']} position={[-0.002, 0.022, -0.008]} rotation={[-2.058, -1.136, -1.357]} scale={0.429} />
              <mesh geometry={nodes.Cube014_139.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.024, -0.008]} rotation={[-1.089, -0.296, -0.036]} scale={0.429} />
              <mesh geometry={nodes.Cube014_140.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.026, -0.01]} rotation={[-1.142, -0.105, 0.029]} scale={0.429} />
              <mesh geometry={nodes.Cube014_141.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.027, -0.01]} rotation={[-1.295, -0.386, -0.181]} scale={0.429} />
              <mesh geometry={nodes.Cube014_142.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.028, -0.012]} rotation={[-1.527, -0.671, -0.486]} scale={0.429} />
              <mesh geometry={nodes.Cube014_143.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.03, -0.014]} rotation={[-1.526, -0.496, -0.382]} scale={0.429} />
              <mesh geometry={nodes.Cube014_144.geometry} material={materials['leaf 02.007']} position={[-0.002, 0.03, -0.015]} rotation={[-2.337, -0.945, -1.408]} scale={0.429} />
              <mesh geometry={nodes.Cube014_145.geometry} material={materials['leaf 02.007']} position={[-0.002, 0.032, -0.017]} rotation={[-2.86, -0.857, -2.007]} scale={0.429} />
              <mesh geometry={nodes.Cube014_146.geometry} material={materials['leaf 02.007']} position={[-0.001, 0.033, -0.019]} rotation={[-2.591, -0.863, -1.711]} scale={0.429} />
              <mesh geometry={nodes.Cube014_147.geometry} material={materials['leaf 02.007']} position={[0, 0.034, -0.02]} rotation={[2.982, -0.387, -2.615]} scale={0.429} />
              <mesh geometry={nodes.Cube014_148.geometry} material={materials['leaf 02.007']} position={[0, 0.036, -0.022]} rotation={[3.126, -0.445, -2.473]} scale={0.429} />
              <mesh geometry={nodes.Cube014_149.geometry} material={materials['leaf 02.007']} position={[0.001, 0.038, -0.024]} rotation={[-2.932, -0.513, -2.307]} scale={0.429} />
              <mesh geometry={nodes.Cube014_150.geometry} material={materials['leaf 02.007']} position={[0.001, 0.038, -0.024]} rotation={[-2.686, -0.518, -2.114]} scale={0.429} />
              <mesh geometry={nodes.Cube014_151.geometry} material={materials['leaf 02.007']} position={[0.002, 0.04, -0.025]} rotation={[-2.889, -0.211, -2.36]} scale={0.429} />
              <mesh geometry={nodes.Cube014_152.geometry} material={materials['leaf 02.007']} position={[0.003, 0.042, -0.026]} rotation={[-2.839, -0.17, -2.013]} scale={0.429} />
              <mesh geometry={nodes.Cube014_153.geometry} material={materials['leaf 02.007']} position={[0.004, 0.042, -0.026]} rotation={[2.794, 0.295, -2.367]} scale={0.429} />
              <mesh geometry={nodes.Cube014_154.geometry} material={materials['leaf 02.007']} position={[0.006, 0.044, -0.027]} rotation={[2.023, 0.777, -2.4]} scale={0.429} />
              <mesh geometry={nodes.Cube014_155.geometry} material={materials['leaf 02.007']} position={[0.009, 0.045, -0.029]} rotation={[1.643, 0.838, -2.373]} scale={0.429} />
              <mesh geometry={nodes.Cube014_156.geometry} material={materials['leaf 02.007']} position={[0.009, 0.045, -0.031]} rotation={[-0.666, 1.119, -1.102]} scale={0.429} />
              <mesh geometry={nodes.Cube014_157.geometry} material={materials['leaf 02.007']} position={[0.009, 0.045, -0.031]} rotation={[-1.639, 0.63, -0.807]} scale={0.429} />
              <mesh geometry={nodes.Cube014_158.geometry} material={materials['leaf 02.007']} position={[0.011, 0.044, -0.033]} rotation={[-2.366, 0.207, -0.89]} scale={0.429} />
              <mesh geometry={nodes.Cube014_159.geometry} material={materials['leaf 02.007']} position={[0.013, 0.043, -0.033]} rotation={[2.769, -0.174, -1.634]} scale={0.429} />
              <mesh geometry={nodes.Cube014_160.geometry} material={materials['leaf 02.007']} position={[0.015, 0.043, -0.034]} rotation={[1.998, -0.022, -2.197]} scale={0.429} />
              <mesh geometry={nodes.Cube014_161.geometry} material={materials['leaf 02.007']} position={[0.017, 0.042, -0.037]} rotation={[1.751, 0.013, -2.484]} scale={0.429} />
              <mesh geometry={nodes.Cube014_162.geometry} material={materials['leaf 02.007']} position={[0.018, 0.042, -0.038]} rotation={[1.381, 0.573, -2.935]} scale={0.429} />
              <mesh geometry={nodes.Cube014_163.geometry} material={materials['leaf 02.007']} position={[0.019, 0.041, -0.04]} rotation={[1.429, 0.334, -3.072]} scale={0.429} />
              <mesh geometry={nodes.Cube014_164.geometry} material={materials['leaf 02.007']} position={[0.019, 0.039, -0.042]} rotation={[1.454, 0.499, 2.839]} scale={0.429} />
              <mesh geometry={nodes.Cube014_165.geometry} material={materials['leaf 02.007']} position={[0.019, 0.038, -0.043]} rotation={[1.419, 0.328, 2.923]} scale={0.429} />
              <mesh geometry={nodes.Cube014_166.geometry} material={materials['leaf 02.007']} position={[0.019, 0.036, -0.044]} rotation={[1.376, -0.225, -2.977]} scale={0.429} />
              <mesh geometry={nodes.Cube014_167.geometry} material={materials['leaf 02.007']} position={[0.018, 0.034, -0.046]} rotation={[2.892, -0.801, -0.845]} scale={0.429} />
              <mesh geometry={nodes.Cube014_168.geometry} material={materials['leaf 02.007']} position={[0.018, 0.032, -0.048]} rotation={[2.683, 1.007, 0.846]} scale={0.429} />
              <mesh geometry={nodes.Cube014_169.geometry} material={materials['leaf 02.007']} position={[0.019, 0.03, -0.048]} rotation={[1.747, -0.863, -1.902]} scale={0.429} />
              <mesh geometry={nodes.Cube014_170.geometry} material={materials['leaf 02.007']} position={[0.02, 0.025, -0.051]} rotation={[0.936, 0.903, 2.542]} scale={0.429} />
              <mesh geometry={nodes.Cube014_171.geometry} material={materials['leaf 02.007']} position={[0.019, 0.024, -0.051]} rotation={[2.71, 0.284, -0.041]} scale={0.429} />
              <mesh geometry={nodes.Cube014_172.geometry} material={materials['leaf 02.007']} position={[0.02, 0.018, -0.05]} rotation={[2.51, -0.011, -0.227]} scale={0.429} />
              <mesh geometry={nodes.Cube014_173.geometry} material={materials['leaf 02.007']} position={[0.002, 0.016, 0.002]} rotation={[-1.675, 0.094, -2.037]} scale={0.429} />
              <mesh geometry={nodes.Cube014_174.geometry} material={materials['leaf 02.007']} position={[0.003, 0.019, 0.003]} rotation={[-0.724, -0.218, -1.158]} scale={0.429} />
              <mesh geometry={nodes.Cube014_175.geometry} material={materials['leaf 02.007']} position={[0.004, 0.019, 0.004]} rotation={[-2.643, 0.939, -2.939]} scale={0.429} />
              <mesh geometry={nodes.Cube014_176.geometry} material={materials['leaf 02.007']} position={[0.004, 0.022, 0.004]} rotation={[-0.653, -0.258, -0.548]} scale={0.429} />
              <mesh geometry={nodes.Cube014_177.geometry} material={materials['leaf 02.007']} position={[0.006, 0.022, 0.005]} rotation={[-2.672, 0.429, -3.062]} scale={0.429} />
              <mesh geometry={nodes.Cube014_178.geometry} material={materials['leaf 02.007']} position={[0.005, 0.025, 0.004]} rotation={[-0.783, 0.509, -0.038]} scale={0.429} />
              <mesh geometry={nodes.Cube014_179.geometry} material={materials['leaf 02.007']} position={[0.007, 0.027, 0.004]} rotation={[-3.108, 0.515, -3.052]} scale={0.429} />
              <mesh geometry={nodes.Cube014_180.geometry} material={materials['leaf 02.007']} position={[0.008, 0.028, 0.001]} rotation={[-2.381, -0.539, -1.671]} scale={0.429} />
              <mesh geometry={nodes.Cube014_181.geometry} material={materials['leaf 02.007']} position={[0.008, 0.029, 0]} rotation={[-2.292, -0.459, -1.476]} scale={0.429} />
              <mesh geometry={nodes.Cube014_182.geometry} material={materials['leaf 02.007']} position={[0.01, 0.03, 0]} rotation={[2.93, 0.103, -2.484]} scale={0.429} />
              <mesh geometry={nodes.Cube014_183.geometry} material={materials['leaf 02.007']} position={[0.01, 0.032, 0]} rotation={[2.217, 1.162, -2.796]} scale={0.429} />
              <mesh geometry={nodes.Cube014_184.geometry} material={materials['leaf 02.007']} position={[0.012, 0.033, -0.002]} rotation={[1.181, 1.355, -1.984]} scale={0.429} />
              <mesh geometry={nodes.Cube014_185.geometry} material={materials['leaf 02.007']} position={[0.014, 0.034, -0.003]} rotation={[1.405, 1.186, -2.056]} scale={0.429} />
              <mesh geometry={nodes.Cube014_186.geometry} material={materials['leaf 02.007']} position={[0.015, 0.034, -0.003]} rotation={[1.551, 1.014, -2.057]} scale={0.429} />
              <mesh geometry={nodes.Cube014_187.geometry} material={materials['leaf 02.007']} position={[0.016, 0.034, -0.004]} rotation={[2.186, 0.7, -2.08]} scale={0.429} />
              <mesh geometry={nodes.Cube014_188.geometry} material={materials['leaf 02.007']} position={[0.019, 0.034, -0.005]} rotation={[-3.017, 0.329, -1.866]} scale={0.429} />
              <mesh geometry={nodes.Cube014_189.geometry} material={materials['leaf 02.007']} position={[0.02, 0.034, -0.005]} rotation={[2.991, 0.508, -1.918]} scale={0.429} />
              <mesh geometry={nodes.Cube014_190.geometry} material={materials['leaf 02.007']} position={[0.022, 0.035, -0.005]} rotation={[-3.126, 0.536, -1.931]} scale={0.429} />
              <mesh geometry={nodes.Cube014_191.geometry} material={materials['leaf 02.007']} position={[0.024, 0.036, -0.005]} rotation={[2.887, 0.69, -1.984]} scale={0.429} />
              <mesh geometry={nodes.Cube014_192.geometry} material={materials['leaf 02.007']} position={[0.025, 0.038, -0.005]} rotation={[1.087, 0.912, -1.308]} scale={0.429} />
              <mesh geometry={nodes.Cube014_193.geometry} material={materials['leaf 02.007']} position={[0.027, 0.039, -0.006]} rotation={[-0.379, 0.37, -1.096]} scale={0.429} />
              <mesh geometry={nodes.Cube014_194.geometry} material={materials['leaf 02.007']} position={[0.03, 0.041, -0.005]} rotation={[-0.117, 0.465, -1.252]} scale={0.429} />
              <mesh geometry={nodes.Cube014_195.geometry} material={materials['leaf 02.007']} position={[0.032, 0.04, -0.006]} rotation={[-1.25, 0.493, -1.709]} scale={0.429} />
              <mesh geometry={nodes.Cube014_196.geometry} material={materials['leaf 02.007']} position={[0.033, 0.039, -0.004]} rotation={[2.419, 0.613, -1.459]} scale={0.429} />
              <mesh geometry={nodes.Cube014_197.geometry} material={materials['leaf 02.007']} position={[0.038, 0.04, -0.005]} rotation={[-0.317, 0.456, -1.865]} scale={0.429} />
              <mesh geometry={nodes.Cube014_198.geometry} material={materials['leaf 02.007']} position={[0.038, 0.039, -0.003]} rotation={[1.708, 0.424, -1.336]} scale={0.429} />
              <mesh geometry={nodes.Cube014_199.geometry} material={materials['leaf 02.007']} position={[0.042, 0.039, -0.003]} rotation={[-0.484, 0.411, -1.953]} scale={0.429} />
              <mesh geometry={nodes.Cube014_200.geometry} material={materials['leaf 02.007']} position={[0.047, 0.038, -0.002]} rotation={[-1.201, 0.577, -2.201]} scale={0.429} />
              <mesh geometry={nodes.Cube014_201.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.022, 0.009]} rotation={[-1.847, -0.893, 2.963]} scale={0.429} />
              <mesh geometry={nodes.Cube014_202.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.022, 0.011]} rotation={[-1.561, -0.182, 2.608]} scale={0.429} />
              <mesh geometry={nodes.Cube014_203.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.023, 0.012]} rotation={[-1.403, 0.046, 2.436]} scale={0.429} />
              <mesh geometry={nodes.Cube014_204.geometry} material={materials['leaf 02.007']} position={[-0.006, 0.022, 0.013]} rotation={[-0.767, 0.426, 1.8]} scale={0.429} />
              <mesh geometry={nodes.Cube014_205.geometry} material={materials['leaf 02.007']} position={[-0.007, 0.023, 0.014]} rotation={[-0.419, 0.425, 1.447]} scale={0.429} />
              <mesh geometry={nodes.Cube014_206.geometry} material={materials['leaf 02.007']} position={[-0.009, 0.025, 0.016]} rotation={[-0.607, 0.414, 1.612]} scale={0.429} />
              <mesh geometry={nodes.Cube014_207.geometry} material={materials['leaf 02.007']} position={[-0.009, 0.025, 0.017]} rotation={[-0.779, 0.377, 1.77]} scale={0.429} />
              <mesh geometry={nodes.Cube014_208.geometry} material={materials['leaf 02.007']} position={[-0.01, 0.026, 0.019]} rotation={[-0.916, 0.334, 1.875]} scale={0.429} />
              <mesh geometry={nodes.Cube014_209.geometry} material={materials['leaf 02.007']} position={[-0.011, 0.028, 0.02]} rotation={[-1.458, 0.011, 2.331]} scale={0.429} />
              <mesh geometry={nodes.Cube014_210.geometry} material={materials['leaf 02.007']} position={[-0.012, 0.028, 0.021]} rotation={[-1.244, 0.193, 2.119]} scale={0.429} />
              <mesh geometry={nodes.Cube014_211.geometry} material={materials['leaf 02.007']} position={[-0.013, 0.029, 0.022]} rotation={[-1.367, 0.129, 2.194]} scale={0.429} />
              <mesh geometry={nodes.Cube014_212.geometry} material={materials['leaf 02.007']} position={[-0.015, 0.031, 0.024]} rotation={[-1.518, 0.036, 2.287]} scale={0.429} />
              <mesh geometry={nodes.Cube014_213.geometry} material={materials['leaf 02.007']} position={[-0.016, 0.031, 0.025]} rotation={[-1.3, 0.215, 2.071]} scale={0.429} />
              <mesh geometry={nodes.Cube014_214.geometry} material={materials['leaf 02.007']} position={[-0.018, 0.032, 0.025]} rotation={[-0.088, 0.134, 0.999]} scale={0.429} />
              <mesh geometry={nodes.Cube014_215.geometry} material={materials['leaf 02.007']} position={[-0.021, 0.034, 0.027]} rotation={[0.809, -0.719, 0.523]} scale={0.429} />
              <mesh geometry={nodes.Cube014_216.geometry} material={materials['leaf 02.007']} position={[-0.02, 0.036, 0.028]} rotation={[-2.143, -0.986, 2.535]} scale={0.429} />
              <mesh geometry={nodes.Cube014_217.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.036, 0.031]} rotation={[-1.463, -0.45, 2.454]} scale={0.429} />
              <mesh geometry={nodes.Cube014_218.geometry} material={materials['leaf 02.007']} position={[-0.024, 0.034, 0.031]} rotation={[-0.002, 0.189, 1.436]} scale={0.429} />
              <mesh geometry={nodes.Cube014_219.geometry} material={materials['leaf 02.007']} position={[-0.025, 0.036, 0.031]} rotation={[1.339, -0.711, 0.587]} scale={0.429} />
              <mesh geometry={nodes.Cube014_220.geometry} material={materials['leaf 02.007']} position={[-0.026, 0.037, 0.034]} rotation={[-2.233, -1.302, 2.309]} scale={0.429} />
              <mesh geometry={nodes.Cube014_221.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.035, 0.035]} rotation={[-1.081, -0.316, 2.493]} scale={0.429} />
              <mesh geometry={nodes.Cube014_222.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.035, 0.035]} rotation={[0.408, 0.284, 1.29]} scale={0.429} />
              <mesh geometry={nodes.Cube014_223.geometry} material={materials['leaf 02.007']} position={[-0.031, 0.036, 0.038]} rotation={[1.542, -0.836, 0.322]} scale={0.429} />
              <mesh geometry={nodes.Cube014_224.geometry} material={materials['leaf 02.007']} position={[-0.032, 0.035, 0.042]} rotation={[-1.188, -1.161, 3.102]} scale={0.429} />
              <mesh geometry={nodes.Cube014_225.geometry} material={materials['leaf 02.007']} position={[-0.031, 0.034, 0.04]} rotation={[-0.453, 0.271, 2.231]} scale={0.429} />
              <mesh geometry={nodes.Cube014_226.geometry} material={materials['leaf 02.007']} position={[-0.033, 0.034, 0.042]} rotation={[0.81, 0.398, 0.909]} scale={0.429} />
              <mesh geometry={nodes.Cube014_227.geometry} material={materials['leaf 02.007']} position={[-0.035, 0.034, 0.046]} rotation={[1.227, -0.071, 0.218]} scale={0.429} />
              <mesh geometry={nodes.Cube014_228.geometry} material={materials['leaf 02.007']} position={[-0.034, 0.034, 0.047]} rotation={[-0.337, -1.102, -2.201]} scale={0.429} />
              <mesh geometry={nodes.Cube014_229.geometry} material={materials['leaf 02.007']} position={[-0.033, 0.033, 0.048]} rotation={[-0.804, 0.044, 2.943]} scale={0.429} />
              <mesh geometry={nodes.Cube014_230.geometry} material={materials['leaf 02.007']} position={[-0.034, 0.033, 0.052]} rotation={[-0.184, -0.737, -2.227]} scale={0.429} />
              <mesh geometry={nodes.Cube014_231.geometry} material={materials['leaf 02.007']} position={[-0.033, 0.032, 0.053]} rotation={[-0.284, -0.411, -2.46]} scale={0.429} />
              <mesh geometry={nodes.Cube014_232.geometry} material={materials['leaf 02.007']} position={[-0.032, 0.031, 0.055]} rotation={[-0.366, -0.061, -2.663]} scale={0.429} />
              <mesh geometry={nodes.Cube014_233.geometry} material={materials['leaf 02.007']} position={[-0.032, 0.03, 0.055]} rotation={[-0.475, 0.214, -2.81]} scale={0.429} />
              <mesh geometry={nodes.Cube014_234.geometry} material={materials['leaf 02.007']} position={[-0.033, 0.029, 0.056]} rotation={[1.732, 1.199, 0.303]} scale={0.429} />
              <mesh geometry={nodes.Cube014_235.geometry} material={materials['leaf 02.007']} position={[-0.032, 0.027, 0.058]} rotation={[1.829, 0.439, -0.268]} scale={0.429} />
              <mesh geometry={nodes.Cube014_236.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.026, 0.062]} rotation={[0.655, -0.556, -1.66]} scale={0.429} />
              <mesh geometry={nodes.Cube014_237.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.026, 0.059]} rotation={[-0.447, 0.572, -2.924]} scale={0.429} />
              <mesh geometry={nodes.Cube014_238.geometry} material={materials['leaf 02.007']} position={[-0.029, 0.024, 0.062]} rotation={[1.982, 0.866, -0.072]} scale={0.429} />
              <mesh geometry={nodes.Cube014_239.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.022, 0.066]} rotation={[1.162, -0.482, -1.129]} scale={0.429} />
              <mesh geometry={nodes.Cube014_240.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.023, 0.063]} rotation={[-0.422, 0.58, -2.934]} scale={0.429} />
              <mesh geometry={nodes.Cube014_241.geometry} material={materials['leaf 02.007']} position={[-0.027, 0.02, 0.066]} rotation={[1.958, 0.859, -0.038]} scale={0.429} />
              <mesh geometry={nodes.Cube014_242.geometry} material={materials['leaf 02.007']} position={[-0.025, 0.019, 0.069]} rotation={[1.148, -0.52, -1.094]} scale={0.429} />
              <mesh geometry={nodes.Cube014_243.geometry} material={materials['leaf 02.007']} position={[-0.024, 0.019, 0.067]} rotation={[-0.416, 0.556, -2.977]} scale={0.429} />
              <mesh geometry={nodes.Cube014_244.geometry} material={materials['leaf 02.007']} position={[-0.024, 0.017, 0.069]} rotation={[1.551, 1.277, 0.606]} scale={0.429} />
              <mesh geometry={nodes.Cube014_245.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.015, 0.072]} rotation={[-0.439, 0.6, 3.041]} scale={0.429} />
              <mesh geometry={nodes.Cube014_246.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.015, 0.074]} rotation={[0.074, -0.847, -2.172]} scale={0.429} />
              <mesh geometry={nodes.Cube014_247.geometry} material={materials['leaf 02.007']} position={[-0.023, 0.014, 0.076]} rotation={[1.419, -0.614, -0.478]} scale={0.429} />
              <mesh geometry={nodes.Cube014_248.geometry} material={materials['leaf 02.007']} position={[-0.023, 0.012, 0.078]} rotation={[1.51, -0.478, -0.316]} scale={0.429} />
              <mesh geometry={nodes.Cube014_249.geometry} material={materials['leaf 02.007']} position={[-0.023, 0.012, 0.079]} rotation={[1.38, -0.741, -0.575]} scale={0.429} />
              <mesh geometry={nodes.Cube014_250.geometry} material={materials['leaf 02.007']} position={[-0.023, 0.011, 0.081]} rotation={[1.052, -0.958, -1.048]} scale={0.429} />
              <mesh geometry={nodes.Cube014_251.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.009, 0.084]} rotation={[-0.051, -0.802, -2.44]} scale={0.429} />
              <mesh geometry={nodes.Cube014_252.geometry} material={materials['leaf 02.007']} position={[-0.021, 0.008, 0.084]} rotation={[-0.315, -0.104, -3.027]} scale={0.429} />
              <mesh geometry={nodes.Cube014_253.geometry} material={materials['leaf 02.007']} position={[-0.021, 0.007, 0.084]} rotation={[-0.319, 0.22, 3.058]} scale={0.429} />
              <mesh geometry={nodes.Cube014_254.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.004, 0.086]} rotation={[0.085, 0.941, 2.444]} scale={0.429} />
              <mesh geometry={nodes.Cube014_255.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.004, 0.087]} rotation={[1.506, 1.018, 0.746]} scale={0.429} />
              <mesh geometry={nodes.Cube014_256.geometry} material={materials['leaf 02.007']} position={[-0.022, 0.002, 0.088]} rotation={[1.928, 0.771, 0.235]} scale={0.429} />
              <mesh geometry={nodes.Cube014_257.geometry} material={materials['leaf 02.007']} position={[-0.021, 0, 0.092]} rotation={[1.482, -0.585, -1.099]} scale={0.429} />
              <mesh geometry={nodes.Cube014_258.geometry} material={materials['leaf 02.007']} position={[-0.021, 0, 0.089]} rotation={[0.721, 1.332, 1.894]} scale={0.429} />
              <mesh geometry={nodes.Cube014_259.geometry} material={materials['leaf 02.007']} position={[-0.02, -0.002, 0.092]} rotation={[1.716, -0.332, -0.875]} scale={0.429} />
              <mesh geometry={nodes.Cube014_260.geometry} material={materials['leaf 02.007']} position={[-0.018, -0.003, 0.092]} rotation={[-0.05, 0.364, -2.734]} scale={0.429} />
              <mesh geometry={nodes.Cube014_261.geometry} material={materials['leaf 02.007']} position={[-0.019, -0.005, 0.093]} rotation={[2.195, 0.341, -0.492]} scale={0.429} />
              <mesh geometry={nodes.Cube014_262.geometry} material={materials['leaf 02.007']} position={[-0.015, -0.007, 0.095]} rotation={[0.41, -0.076, -2.174]} scale={0.429} />
              <mesh geometry={nodes.Cube014_263.geometry} material={materials['leaf 02.007']} position={[-0.014, -0.008, 0.094]} rotation={[-0.849, 1.255, -2.503]} scale={0.429} />
              <mesh geometry={nodes.Cube014_264.geometry} material={materials['leaf 02.007']} position={[-0.014, -0.009, 0.096]} rotation={[1.605, -0.105, -1.21]} scale={0.429} />
              <mesh geometry={nodes.Cube014_265.geometry} material={materials['leaf 02.007']} position={[-0.011, -0.01, 0.096]} rotation={[0.068, 0.355, -2.273]} scale={0.429} />
              <mesh geometry={nodes.Cube014_266.geometry} material={materials['leaf 02.007']} position={[-0.01, -0.012, 0.096]} rotation={[-2.444, 1.191, -1.221]} scale={0.429} />
              <mesh geometry={nodes.Cube014_267.geometry} material={materials['leaf 02.007']} position={[-0.009, -0.013, 0.098]} rotation={[1.624, 0.006, -1.301]} scale={0.429} />
              <mesh geometry={nodes.Cube014_268.geometry} material={materials['leaf 02.007']} position={[-0.006, -0.014, 0.097]} rotation={[0.066, 0.411, -2.216]} scale={0.429} />
              <mesh geometry={nodes.Cube014_269.geometry} material={materials['leaf 02.007']} position={[-0.005, -0.016, 0.097]} rotation={[-3.125, 0.89, -0.905]} scale={0.429} />
              <mesh geometry={nodes.Cube014_270.geometry} material={materials['leaf 02.007']} position={[-0.004, -0.015, 0.099]} rotation={[1.191, -0.036, -1.61]} scale={0.429} />
              <mesh geometry={nodes.Cube014_271.geometry} material={materials['leaf 02.007']} position={[-0.003, -0.015, 0.097]} rotation={[-0.327, 0.697, -2.296]} scale={0.429} />
              <mesh geometry={nodes.Cube014_272.geometry} material={materials['leaf 02.007']} position={[0, -0.019, 0.099]} rotation={[2.645, 0.588, -0.77]} scale={0.429} />
              <mesh geometry={nodes.Cube014_273.geometry} material={materials['leaf 02.007']} position={[0.002, -0.019, 0.1]} rotation={[0.746, -0.052, -1.934]} scale={0.429} />
              <mesh geometry={nodes.Cube014_274.geometry} material={materials['leaf 02.007']} position={[0.002, -0.02, 0.098]} rotation={[-1.636, 1.248, -1.782]} scale={0.429} />
              <mesh geometry={nodes.Cube014_275.geometry} material={materials['leaf 02.007']} position={[0.004, -0.023, 0.101]} rotation={[1.848, -0.053, -0.974]} scale={0.429} />
              <mesh geometry={nodes.Cube014_276.geometry} material={materials['leaf 02.007']} position={[0.004, -0.021, 0.099]} rotation={[-0.274, 0.761, -2.566]} scale={0.429} />
              <mesh geometry={nodes.Cube014_277.geometry} material={materials['leaf 02.007']} position={[0.007, -0.024, 0.1]} rotation={[-0.117, 0.593, -2.726]} scale={0.429} />
              <mesh geometry={nodes.Cube014_278.geometry} material={materials['leaf 02.007']} position={[0.008, -0.026, 0.102]} rotation={[-0.037, 0.296, -2.887]} scale={0.429} />
              <mesh geometry={nodes.Cube014_279.geometry} material={materials['leaf 02.007']} position={[0.009, -0.027, 0.102]} rotation={[-0.118, 0.525, -3.104]} scale={0.429} />
              <mesh geometry={nodes.Cube014_280.geometry} material={materials['leaf 02.007']} position={[0.009, -0.03, 0.105]} rotation={[-0.139, -0.165, -2.937]} scale={0.429} />
              <mesh geometry={nodes.Cube014_281.geometry} material={materials['leaf 02.007']} position={[0.009, -0.033, 0.108]} rotation={[-0.181, -0.374, -2.889]} scale={0.429} />
              <mesh geometry={nodes.Cube014_282.geometry} material={materials['leaf 02.007']} position={[0.009, -0.034, 0.109]} rotation={[-0.211, -0.547, -2.804]} scale={0.429} />
              <mesh geometry={nodes.Cube014_283.geometry} material={materials['leaf 02.007']} position={[0.009, -0.035, 0.111]} rotation={[1.065, -1.023, -1.062]} scale={0.429} />
              <mesh geometry={nodes.Cube014_284.geometry} material={materials['leaf 02.007']} position={[0.008, -0.038, 0.114]} rotation={[1.194, 0.721, 0.715]} scale={0.429} />
              <mesh geometry={nodes.Cube014_285.geometry} material={materials['leaf 02.007']} position={[0.008, -0.039, 0.117]} rotation={[-0.679, -0.587, -2.961]} scale={0.429} />
              <mesh geometry={nodes.Cube014_286.geometry} material={materials['leaf 02.007']} position={[0.008, -0.04, 0.12]} rotation={[-0.788, 0.179, 2.797]} scale={0.429} />
              <mesh geometry={nodes.Cube014_287.geometry} material={materials['leaf 02.007']} position={[0.009, 0.019, 0.005]} rotation={[-1.722, -0.526, -1.969]} scale={0.429} />
              <mesh geometry={nodes.Cube014_288.geometry} material={materials['leaf 02.007']} position={[0.009, 0.021, 0.008]} rotation={[-0.357, 1.324, 0.557]} scale={0.429} />
              <mesh geometry={nodes.Cube014_289.geometry} material={materials['leaf 02.007']} position={[0.011, 0.022, 0.006]} rotation={[-1.802, -0.44, -2.204]} scale={0.429} />
              <mesh geometry={nodes.Cube014_290.geometry} material={materials['leaf 02.007']} position={[0.011, 0.025, 0.009]} rotation={[-0.1, 0.255, -0.299]} scale={0.429} />
              <mesh geometry={nodes.Cube014_291.geometry} material={materials['leaf 02.007']} position={[0.012, 0.025, 0.01]} rotation={[-1.977, 1.291, 2.527]} scale={0.429} />
              <mesh geometry={nodes.Cube014_292.geometry} material={materials['leaf 02.007']} position={[0.013, 0.029, 0.009]} rotation={[-1.227, -0.641, -1.761]} scale={0.429} />
              <mesh geometry={nodes.Cube014_293.geometry} material={materials['leaf 02.007']} position={[0.014, 0.029, 0.011]} rotation={[-2.127, 0.602, -3.081]} scale={0.429} />
              <mesh geometry={nodes.Cube014_294.geometry} material={materials['leaf 02.007']} position={[0.014, 0.032, 0.012]} rotation={[-1.172, -0.691, -2.092]} scale={0.429} />
              <mesh geometry={nodes.Cube014_295.geometry} material={materials['leaf 02.007']} position={[0.014, 0.032, 0.014]} rotation={[0.382, 0.725, 0.296]} scale={0.429} />
              <mesh geometry={nodes.Cube014_296.geometry} material={materials['leaf 02.007']} position={[0.016, 0.033, 0.015]} rotation={[-1.443, -0.283, -2.808]} scale={0.429} />
              <mesh geometry={nodes.Cube014_297.geometry} material={materials['leaf 02.007']} position={[0.014, 0.035, 0.017]} rotation={[0.195, -0.689, -0.757]} scale={0.429} />
              <mesh geometry={nodes.Cube014_298.geometry} material={materials['leaf 02.007']} position={[0.015, 0.034, 0.019]} rotation={[-0.943, 1.097, 2.075]} scale={0.429} />
              <mesh geometry={nodes.Cube014_299.geometry} material={materials['leaf 02.007']} position={[0.015, 0.037, 0.021]} rotation={[0.172, -0.365, -0.519]} scale={0.429} />
              <mesh geometry={nodes.Cube014_300.geometry} material={materials['leaf 02.007']} position={[0.017, 0.037, 0.022]} rotation={[-1.861, 0.466, -3.116]} scale={0.429} />
              <mesh geometry={nodes.Cube014_301.geometry} material={materials['leaf 02.007']} position={[0.016, 0.039, 0.023]} rotation={[0.238, 0.389, -0.093]} scale={0.429} />
              <mesh geometry={nodes.Cube014_302.geometry} material={materials['leaf 02.007']} position={[0.017, 0.041, 0.024]} rotation={[-0.781, -0.781, -1.676]} scale={0.429} />
              <mesh geometry={nodes.Cube014_303.geometry} material={materials['leaf 02.007']} position={[0.018, 0.04, 0.026]} rotation={[-1.457, 0.876, 2.681]} scale={0.429} />
              <mesh geometry={nodes.Cube014_304.geometry} material={materials['leaf 02.007']} position={[0.017, 0.042, 0.028]} rotation={[0.597, -0.211, -0.265]} scale={0.429} />
              <mesh geometry={nodes.Cube014_305.geometry} material={materials['leaf 02.007']} position={[0.018, 0.043, 0.03]} rotation={[-1.255, -0.383, -2.975]} scale={0.429} />
              <mesh geometry={nodes.Cube014_306.geometry} material={materials['leaf 02.007']} position={[0.017, 0.042, 0.032]} rotation={[0.456, 0.867, 0.926]} scale={0.429} />
              <mesh geometry={nodes.Cube014_307.geometry} material={materials['leaf 02.007']} position={[0.017, 0.042, 0.035]} rotation={[0.879, 0.665, 0.581]} scale={0.429} />
              <mesh geometry={nodes.Cube014_308.geometry} material={materials['leaf 02.007']} position={[0.017, 0.042, 0.04]} rotation={[-0.592, 0.826, 2.287]} scale={0.429} />
              <mesh geometry={nodes.Cube014_309.geometry} material={materials['leaf 02.007']} position={[0.016, 0.042, 0.044]} rotation={[-0.301, 0.973, 1.773]} scale={0.429} />
              <mesh geometry={nodes.Cube014_310.geometry} material={materials['leaf 02.007']} position={[0.007, 0.02, -0.002]} rotation={[-1.644, 0.944, 1.292]} scale={0.429} />
              <mesh geometry={nodes.Cube014_311.geometry} material={materials['leaf 02.007']} position={[0.008, 0.023, -0.003]} rotation={[-2.536, 0.709, 2.312]} scale={0.429} />
              <mesh geometry={nodes.Cube014_312.geometry} material={materials['leaf 02.007']} position={[0.007, 0.023, -0.003]} rotation={[-1.53, 0.793, 1.116]} scale={0.429} />
              <mesh geometry={nodes.Cube014_313.geometry} material={materials['leaf 02.007']} position={[0.006, 0.025, -0.005]} rotation={[-0.974, 0.195, 0.338]} scale={0.429} />
              <mesh geometry={nodes.Cube014_314.geometry} material={materials['leaf 02.007']} position={[0.006, 0.026, -0.006]} rotation={[-1.088, -0.941, -0.534]} scale={0.429} />
              <mesh geometry={nodes.Cube014_315.geometry} material={materials['leaf 02.007']} position={[0.007, 0.027, -0.007]} rotation={[-2.907, -0.705, -2.879]} scale={0.429} />
              <mesh geometry={nodes.Cube014_316.geometry} material={materials['leaf 02.007']} position={[0.006, 0.03, -0.006]} rotation={[-2.735, 0.468, 2.58]} scale={0.429} />
              <mesh geometry={nodes.Cube014_317.geometry} material={materials['leaf 02.007']} position={[0.005, 0.034, -0.007]} rotation={[-1.335, 0.718, 0.877]} scale={0.429} />
              <mesh geometry={nodes.Cube014_318.geometry} material={materials['leaf 02.007']} position={[0.004, 0.034, -0.009]} rotation={[-0.881, -0.326, -0.077]} scale={0.429} />
              <mesh geometry={nodes.Cube014_319.geometry} material={materials['leaf 02.007']} position={[0.004, 0.034, -0.009]} rotation={[-0.948, -0.637, -0.313]} scale={0.429} />
              <mesh geometry={nodes.Cube014_320.geometry} material={materials['leaf 02.007']} position={[0.004, 0.037, -0.01]} rotation={[-0.89, -0.418, -0.282]} scale={0.429} />
              <mesh geometry={nodes.Cube014_321.geometry} material={materials['leaf 02.007']} position={[0.004, 0.04, -0.009]} rotation={[-0.746, 0.721, 0.178]} scale={0.429} />
              <mesh geometry={nodes.Cube014_322.geometry} material={materials['leaf 02.007']} position={[0.006, 0.042, -0.009]} rotation={[2.431, 1.301, -2.285]} scale={0.429} />
              <mesh geometry={nodes.Cube014_323.geometry} material={materials['leaf 02.007']} position={[0.008, 0.043, -0.009]} rotation={[0.827, 0.685, -1.148]} scale={0.429} />
              <mesh geometry={nodes.Cube014_324.geometry} material={materials['leaf 02.007']} position={[0.01, 0.044, -0.009]} rotation={[0.134, 0.329, -1.313]} scale={0.429} />
              <mesh geometry={nodes.Cube014_325.geometry} material={materials['leaf 02.007']} position={[0.013, 0.044, -0.009]} rotation={[-1.626, 0.148, -1.905]} scale={0.429} />
              <mesh geometry={nodes.Cube014_326.geometry} material={materials['leaf 02.007']} position={[-0.009, 0.023, -0.003]} rotation={[-1.693, 0.681, 1.462]} scale={0.429} />
              <mesh geometry={nodes.Cube014_327.geometry} material={materials['leaf 02.007']} position={[-0.01, 0.023, -0.005]} rotation={[-0.741, -0.967, -0.244]} scale={0.429} />
              <mesh geometry={nodes.Cube014_328.geometry} material={materials['leaf 02.007']} position={[-0.01, 0.026, -0.003]} rotation={[-2.057, 0.663, 1.861]} scale={0.429} />
              <mesh geometry={nodes.Cube014_329.geometry} material={materials['leaf 02.007']} position={[-0.01, 0.028, -0.006]} rotation={[-2.844, -0.97, -2.887]} scale={0.429} />
              <mesh geometry={nodes.Cube014_330.geometry} material={materials['leaf 02.007']} position={[-0.012, 0.028, -0.005]} rotation={[-0.696, -0.526, 0.068]} scale={0.429} />
              <mesh geometry={nodes.Cube014_331.geometry} material={materials['leaf 02.007']} position={[-0.011, 0.031, -0.006]} rotation={[-2.875, -0.372, 2.978]} scale={0.429} />
              <mesh geometry={nodes.Cube014_332.geometry} material={materials['leaf 02.007']} position={[-0.013, 0.033, -0.007]} rotation={[-0.758, -1.111, -0.393]} scale={0.429} />
              <mesh geometry={nodes.Cube014_333.geometry} material={materials['leaf 02.007']} position={[-0.012, 0.035, -0.007]} rotation={[-2.833, -0.783, 3.068]} scale={0.429} />
              <mesh geometry={nodes.Cube014_334.geometry} material={materials['leaf 02.007']} position={[-0.013, 0.037, -0.006]} rotation={[-2.595, -0.091, 2.621]} scale={0.429} />
              <mesh geometry={nodes.Cube014_335.geometry} material={materials['leaf 02.007']} position={[-0.015, 0.04, -0.007]} rotation={[-2.787, -0.677, 2.92]} scale={0.429} />
              <mesh geometry={nodes.Cube014_336.geometry} material={materials['leaf 02.007']} position={[-0.017, 0.041, -0.007]} rotation={[-0.377, -0.933, -0.038]} scale={0.429} />
              <mesh geometry={nodes.Cube014_337.geometry} material={materials['leaf 02.007']} position={[-0.018, 0.044, -0.007]} rotation={[-0.531, -0.82, -0.058]} scale={0.429} />
              <mesh geometry={nodes.Cube014_338.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.016, 0.005]} rotation={[1.241, -1.512, 1.708]} scale={0.429} />
              <mesh geometry={nodes.Cube014_339.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.017, 0.006]} rotation={[-2.382, -0.969, -2.826]} scale={0.429} />
              <mesh geometry={nodes.Cube014_340.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.02, 0.007]} rotation={[-2.202, 0.22, 2.711]} scale={0.429} />
              <mesh geometry={nodes.Cube014_341.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.023, 0.009]} rotation={[-0.866, 0.793, 1.267]} scale={0.429} />
              <mesh geometry={nodes.Cube014_342.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.022, 0.007]} rotation={[-0.371, -0.975, -0.587]} scale={0.429} />
              <mesh geometry={nodes.Cube014_343.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.025, 0.009]} rotation={[-2.039, -0.621, -2.866]} scale={0.429} />
              <mesh geometry={nodes.Cube014_344.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.028, 0.012]} rotation={[-1.82, 0.566, 2.682]} scale={0.429} />
              <mesh geometry={nodes.Cube014_345.geometry} material={materials['leaf 02.007']} position={[-0.007, 0.027, 0.01]} rotation={[0.026, -0.046, 0.048]} scale={0.429} />
              <mesh geometry={nodes.Cube014_346.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.03, 0.012]} rotation={[-1.461, -0.929, -2.233]} scale={0.429} />
              <mesh geometry={nodes.Cube014_347.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.032, 0.015]} rotation={[-1.735, 0.612, 2.749]} scale={0.429} />
              <mesh geometry={nodes.Cube014_348.geometry} material={materials['leaf 02.007']} position={[-0.007, 0.031, 0.014]} rotation={[0.157, 0.002, -0.018]} scale={0.429} />
              <mesh geometry={nodes.Cube014_349.geometry} material={materials['leaf 02.007']} position={[-0.006, 0.034, 0.015]} rotation={[-0.593, -0.951, -1.325]} scale={0.429} />
              <mesh geometry={nodes.Cube014_350.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.036, 0.019]} rotation={[-1.779, 0.208, 3.115]} scale={0.429} />
              <mesh geometry={nodes.Cube014_351.geometry} material={materials['leaf 02.007']} position={[-0.006, 0.035, 0.018]} rotation={[0.215, 0.47, 0.223]} scale={0.429} />
              <mesh geometry={nodes.Cube014_352.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.038, 0.02]} rotation={[-0.539, -0.907, -1.35]} scale={0.429} />
              <mesh geometry={nodes.Cube014_353.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.04, 0.024]} rotation={[-1.726, 0.23, 3.138]} scale={0.429} />
              <mesh geometry={nodes.Cube014_354.geometry} material={materials['leaf 02.007']} position={[-0.006, 0.039, 0.023]} rotation={[0.292, 0.487, 0.186]} scale={0.429} />
              <mesh geometry={nodes.Cube014_355.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.042, 0.024]} rotation={[0.023, -0.647, -0.714]} scale={0.429} />
              <mesh geometry={nodes.Cube014_356.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.043, 0.028]} rotation={[0.365, 0.359, 0.023]} scale={0.429} />
              <mesh geometry={nodes.Cube014_357.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.045, 0.028]} rotation={[-0.034, -0.683, -0.936]} scale={0.429} />
              <mesh geometry={nodes.Cube014_358.geometry} material={materials['leaf 02.007']} position={[-0.004, 0.046, 0.031]} rotation={[0.139, -0.542, -0.923]} scale={0.429} />
              <mesh geometry={nodes.Cube014_359.geometry} material={materials['leaf 02.007']} position={[-0.003, 0.046, 0.034]} rotation={[0.472, 0.314, 0]} scale={0.429} />
              <mesh geometry={nodes.Cube014_360.geometry} material={materials['leaf 02.007']} position={[-0.002, 0.047, 0.036]} rotation={[-1.478, -0.327, -2.868]} scale={0.429} />
              <mesh geometry={nodes.Cube014_361.geometry} material={materials['leaf 02.007']} position={[0.007, 0.016, 0]} rotation={[-0.67, -0.229, -1.459]} scale={0.429} />
              <mesh geometry={nodes.Cube014_362.geometry} material={materials['leaf 02.007']} position={[0.008, 0.016, 0.002]} rotation={[0.41, 0.895, -0.61]} scale={0.429} />
              <mesh geometry={nodes.Cube014_363.geometry} material={materials['leaf 02.007']} position={[0.011, 0.019, 0.002]} rotation={[-0.84, -0.157, -1.509]} scale={0.429} />
              <mesh geometry={nodes.Cube014_364.geometry} material={materials['leaf 02.007']} position={[0.01, 0.016, 0.002]} rotation={[-2.239, 0.545, -2.494]} scale={0.429} />
              <mesh geometry={nodes.Cube014_365.geometry} material={materials['leaf 02.007']} position={[0.014, 0.02, 0.006]} rotation={[2.458, 1.194, -2.021]} scale={0.429} />
              <mesh geometry={nodes.Cube014_366.geometry} material={materials['leaf 02.007']} position={[0.013, 0.02, 0.004]} rotation={[0.077, 0.258, -0.919]} scale={0.429} />
              <mesh geometry={nodes.Cube014_367.geometry} material={materials['leaf 02.007']} position={[0.017, 0.022, 0.005]} rotation={[-1.238, 0.016, -1.894]} scale={0.429} />
              <mesh geometry={nodes.Cube014_368.geometry} material={materials['leaf 02.007']} position={[0.017, 0.021, 0.006]} rotation={[-2.585, 0.756, -2.289]} scale={0.429} />
              <mesh geometry={nodes.Cube014_369.geometry} material={materials['leaf 02.007']} position={[0.018, 0.023, 0.007]} rotation={[0.923, 0.857, -0.915]} scale={0.429} />
              <mesh geometry={nodes.Cube014_370.geometry} material={materials['leaf 02.007']} position={[0.021, 0.025, 0.007]} rotation={[-0.432, 0.09, -1.346]} scale={0.429} />
              <mesh geometry={nodes.Cube014_371.geometry} material={materials['leaf 02.007']} position={[0.023, 0.024, 0.008]} rotation={[-2.703, 0.763, -2.242]} scale={0.429} />
              <mesh geometry={nodes.Cube014_372.geometry} material={materials['leaf 02.007']} position={[0.023, 0.026, 0.008]} rotation={[-0.31, 0.184, -1.175]} scale={0.429} />
              <mesh geometry={nodes.Cube014_373.geometry} material={materials['leaf 02.007']} position={[0.024, 0.024, 0.008]} rotation={[-2.393, 0.536, -2.202]} scale={0.429} />
              <mesh geometry={nodes.Cube014_374.geometry} material={materials['leaf 02.007']} position={[0.027, 0.027, 0.01]} rotation={[0.734, 0.839, -1.029]} scale={0.429} />
              <mesh geometry={nodes.Cube014_375.geometry} material={materials['leaf 02.007']} position={[0.028, 0.029, 0.009]} rotation={[-0.102, 0.368, -1.298]} scale={0.429} />
              <mesh geometry={nodes.Cube014_376.geometry} material={materials['leaf 02.007']} position={[0.029, 0.027, 0.009]} rotation={[-1.974, 0.212, -1.987]} scale={0.429} />
              <mesh geometry={nodes.Cube014_377.geometry} material={materials['leaf 02.007']} position={[0.035, 0.031, 0.011]} rotation={[2.845, 0.869, -2.258]} scale={0.429} />
              <mesh geometry={nodes.Cube014_378.geometry} material={materials['leaf 02.007']} position={[0.033, 0.031, 0.01]} rotation={[-0.108, 0.573, -0.895]} scale={0.429} />
              <mesh geometry={nodes.Cube014_379.geometry} material={materials['leaf 02.007']} position={[0.037, 0.033, 0.01]} rotation={[-1.394, -0.078, -1.679]} scale={0.429} />
              <mesh geometry={nodes.Cube014_380.geometry} material={materials['leaf 02.007']} position={[0.037, 0.033, 0.01]} rotation={[-1.817, -0.048, -1.903]} scale={0.429} />
              <mesh geometry={nodes.Cube014_381.geometry} material={materials['leaf 02.007']} position={[0.04, 0.035, 0.011]} rotation={[-1.1, -0.023, -1.83]} scale={0.429} />
              <mesh geometry={nodes.Cube014_382.geometry} material={materials['leaf 02.007']} position={[0.042, 0.036, 0.012]} rotation={[-0.794, -0.207, -1.964]} scale={0.429} />
              <mesh geometry={nodes.Cube014_383.geometry} material={materials['leaf 02.007']} position={[0.045, 0.036, 0.016]} rotation={[-0.81, -0.227, -2.379]} scale={0.429} />
              <mesh geometry={nodes.Cube014_384.geometry} material={materials['leaf 02.007']} position={[0.044, 0.035, 0.014]} rotation={[-1.668, 1.037, -2.712]} scale={0.429} />
              <mesh geometry={nodes.Cube014_385.geometry} material={materials['leaf 02.007']} position={[0.046, 0.034, 0.018]} rotation={[1.019, 1.185, 0.628]} scale={0.429} />
              <mesh geometry={nodes.Cube014_386.geometry} material={materials['leaf 02.007']} position={[0.047, 0.033, 0.022]} rotation={[1.639, 0.624, 0.041]} scale={0.429} />
              <mesh geometry={nodes.Cube014_387.geometry} material={materials['leaf 02.007']} position={[0.049, 0.033, 0.023]} rotation={[0.348, -0.62, -1.861]} scale={0.429} />
              <mesh geometry={nodes.Cube014_388.geometry} material={materials['leaf 02.007']} position={[0.05, 0.03, 0.026]} rotation={[-0.383, 0.36, -2.996]} scale={0.429} />
              <mesh geometry={nodes.Cube014_389.geometry} material={materials['leaf 02.007']} position={[0.052, 0.026, 0.03]} rotation={[-0.206, 0.027, -2.838]} scale={0.429} />
              <mesh geometry={nodes.Cube014_390.geometry} material={materials['leaf 02.007']} position={[0.052, 0.025, 0.031]} rotation={[-0.19, 0.629, 3.084]} scale={0.429} />
              <mesh geometry={nodes.Cube014_391.geometry} material={materials['leaf 02.007']} position={[0.052, 0.024, 0.031]} rotation={[1.413, 1.247, 0.963]} scale={0.429} />
              <mesh geometry={nodes.Cube014_392.geometry} material={materials['leaf 02.007']} position={[0.004, 0.018, 0.018]} rotation={[-1.06, 0.674, 1.252]} scale={0.429} />
              <mesh geometry={nodes.Cube014_393.geometry} material={materials['leaf 02.007']} position={[0.004, 0.017, 0.016]} rotation={[-0.479, -1.083, -0.485]} scale={0.429} />
              <mesh geometry={nodes.Cube014_394.geometry} material={materials['leaf 02.007']} position={[0.005, 0.02, 0.017]} rotation={[-2.341, -0.657, -3.021]} scale={0.429} />
              <mesh geometry={nodes.Cube014_395.geometry} material={materials['leaf 02.007']} position={[0.004, 0.023, 0.02]} rotation={[-1.94, 0.511, 2.582]} scale={0.429} />
              <mesh geometry={nodes.Cube014_396.geometry} material={materials['leaf 02.007']} position={[0.003, 0.022, 0.019]} rotation={[-0.151, -0.125, 0.13]} scale={0.429} />
              <mesh geometry={nodes.Cube014_397.geometry} material={materials['leaf 02.007']} position={[0.003, 0.025, 0.019]} rotation={[-0.803, -1.112, -1.264]} scale={0.429} />
              <mesh geometry={nodes.Cube014_398.geometry} material={materials['leaf 02.007']} position={[0.004, 0.028, 0.022]} rotation={[-1.981, 0.139, 3.012]} scale={0.429} />
              <mesh geometry={nodes.Cube014_399.geometry} material={materials['leaf 02.007']} position={[0.002, 0.028, 0.024]} rotation={[-0.246, 0.802, 0.752]} scale={0.429} />
              <mesh geometry={nodes.Cube014_400.geometry} material={materials['leaf 02.007']} position={[0.002, 0.03, 0.022]} rotation={[-0.12, -0.743, -0.578]} scale={0.429} />
              <mesh geometry={nodes.Cube014_401.geometry} material={materials['leaf 02.007']} position={[0.004, 0.033, 0.026]} rotation={[-1.839, -0.274, -2.938]} scale={0.429} />
              <mesh geometry={nodes.Cube014_402.geometry} material={materials['leaf 02.007']} position={[0.002, 0.033, 0.027]} rotation={[-0.088, 0.855, 0.687]} scale={0.429} />
              <mesh geometry={nodes.Cube014_403.geometry} material={materials['leaf 02.007']} position={[0.002, 0.034, 0.026]} rotation={[-0.053, -0.696, -0.641]} scale={0.429} />
              <mesh geometry={nodes.Cube014_404.geometry} material={materials['leaf 02.007']} position={[0.004, 0.037, 0.03]} rotation={[-1.735, -0.247, -2.901]} scale={0.429} />
              <mesh geometry={nodes.Cube014_405.geometry} material={materials['leaf 02.007']} position={[0.003, 0.037, 0.032]} rotation={[0.068, 0.872, 0.638]} scale={0.429} />
              <mesh geometry={nodes.Cube014_406.geometry} material={materials['leaf 02.007']} position={[0.003, 0.038, 0.031]} rotation={[0.004, -0.648, -0.728]} scale={0.429} />
              <mesh geometry={nodes.Cube014_407.geometry} material={materials['leaf 02.007']} position={[0.005, 0.04, 0.035]} rotation={[-1.677, -0.273, -2.95]} scale={0.429} />
              <mesh geometry={nodes.Cube014_408.geometry} material={materials['leaf 02.007']} position={[0.004, 0.04, 0.037]} rotation={[0.275, 0.831, 0.692]} scale={0.429} />
              <mesh geometry={nodes.Cube014_409.geometry} material={materials['leaf 02.007']} position={[0.003, 0.041, 0.036]} rotation={[0.07, -0.531, -0.916]} scale={0.429} />
              <mesh geometry={nodes.Cube014_410.geometry} material={materials['leaf 02.007']} position={[0.004, 0.042, 0.04]} rotation={[0.214, -0.064, -0.291]} scale={0.429} />
              <mesh geometry={nodes.Cube014_411.geometry} material={materials['leaf 02.007']} position={[0.005, 0.042, 0.042]} rotation={[-1.551, 1.054, 2.581]} scale={0.429} />
              <mesh geometry={nodes.Cube014_412.geometry} material={materials['leaf 02.007']} position={[0.004, 0.045, 0.043]} rotation={[-0.171, -0.594, -0.839]} scale={0.429} />
              <mesh geometry={nodes.Cube014_413.geometry} material={materials['leaf 02.007']} position={[0.006, 0.047, 0.046]} rotation={[-1.949, 0.685, 2.776]} scale={0.429} />
              <mesh geometry={nodes.Cube014_414.geometry} material={materials['leaf 02.007']} position={[0.005, 0.048, 0.047]} rotation={[0.074, 0.562, 0.051]} scale={0.429} />
              <mesh geometry={nodes.Cube014_415.geometry} material={materials['leaf 02.007']} position={[0.006, 0.052, 0.048]} rotation={[-1.576, 1.155, 1.931]} scale={0.429} />
            </mesh>
            <mesh geometry={nodes.Circle001.geometry} material={materials['stones.007']} position={[0, 0.002, 0]} />
            <mesh geometry={nodes.Cube014_2.geometry} material={materials['leaf 02.007']} position={[-0.005, 0.001, 0.014]} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.Cube012.geometry} material={materials['wood.009']} position={[-0.001, -0.113, 0.115]}>
          <group position={[0.24, 0.008, -0.071]}>
            <mesh geometry={nodes.Cube028.geometry} material={materials['cover.015']} />
            <mesh geometry={nodes.Cube028_1.geometry} material={materials['page.007']} />
          </group>
          <group position={[0.262, 0.008, -0.041]}>
            <mesh geometry={nodes.Cube027.geometry} material={materials['cover.014']} />
            <mesh geometry={nodes.Cube027_1.geometry} material={materials['page.007']} />
          </group>
          <mesh geometry={nodes.Cube017_1.geometry} material={materials['box.007']} position={[-0.163, 0.084, -0.083]}>
            <mesh geometry={nodes.Plane019_2.geometry} material={nodes.Plane019_2.material} position={[0, 0, 0.029]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Plane020.geometry} material={nodes.Plane020.material} position={[0, 0, 0.029]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
            <mesh geometry={nodes.Plane021_1.geometry} material={nodes.Plane021_1.material} position={[0, 0, 0.03]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.Cube013.geometry} material={materials['wood.009']} position={[0.294, 0, 0]}>
          <mesh geometry={nodes.BezierCurve003.geometry} material={materials['metalic.007']} position={[0, 0.267, 0.053]} rotation={[Math.PI, 0, -Math.PI / 2]} />
        </mesh>
      </group>
      <group position={[2.021, 0, -2.207]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['Material.008']} position={[0, 0.221, 0]} />
        <group position={[0.009, 0.338, 0.239]}>
          <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.009']} />
        </group>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.006']} position={[-0.452, 0.995, -0.871]} />
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.006']} position={[0.393, 0.995, -0.871]} />
        <mesh geometry={nodes.Icosphere003.geometry} material={materials['Material.008']} position={[-0.836, 0.404, -1.079]} />
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.007']} position={[-0.028, 0.444, 0.407]} />
        <mesh geometry={nodes.Plane004.geometry} material={materials['Material.010']} position={[0.007, 0.213, 0.001]} />
        <mesh geometry={nodes.Plane008.geometry} material={materials['Material.008']} position={[0, 0.404, -1.057]} />
      </group>
      <group position={[0.008, 1.231, 3.1]} rotation={[0, Math.PI / 2, 0]} scale={1.524}>
        <mesh geometry={nodes.Untitled075.geometry} material={materials['aluminium.001']} />
        <mesh geometry={nodes.Untitled075_1.geometry} material={materials.rubber} />
        <mesh geometry={nodes.Untitled075_2.geometry} material={materials['black plastic']} />
        <mesh geometry={nodes.Untitled075_3.geometry} material={materials['glass.001']} />
        <mesh geometry={nodes.Untitled075_4.geometry} material={materials['glass frame']} />
        <mesh geometry={nodes.Untitled075_5.geometry} material={materials['display frame']} />
        <mesh geometry={nodes.Untitled075_6.geometry} material={materials.display} />
        <mesh geometry={nodes.Untitled075_7.geometry} material={materials['white plastic']} />
        <mesh geometry={nodes.Untitled075_8.geometry} material={materials.metal} />
        <mesh geometry={nodes.Untitled075_9.geometry} material={materials['yellow metal']} />
        <mesh geometry={nodes.Untitled075_10.geometry} material={materials.camera} />
        <mesh geometry={nodes.Untitled075_11.geometry} material={materials['keys left']} />
        <mesh geometry={nodes.Untitled075_12.geometry} material={materials['keys left']} />
        <mesh geometry={nodes.Untitled075_13.geometry} material={materials['glossy white plastic']} />
        <mesh geometry={nodes.Untitled075_14.geometry} material={materials['matt white plastic']} />
        <mesh geometry={nodes.Untitled075_15.geometry} material={materials['rubber.001']} />
        <mesh geometry={nodes.Untitled075_16.geometry} material={materials['plastic black']} />
        <mesh geometry={nodes.Untitled075_17.geometry} material={materials['plastic green']} />
        <mesh geometry={nodes.Untitled075_18.geometry} material={materials['switch top']} />
        <mesh geometry={nodes.Untitled075_19.geometry} material={materials['chrome.002']} />
        <mesh geometry={nodes.Untitled075_20.geometry} material={materials['plastic top']} />
      </group>
      <group position={[0.309, 0, 1.631]} scale={2.12}>
        <group position={[0, 0.526, 0.045]} scale={[0.154, 0.202, 0.255]}>
          <mesh geometry={nodes.Cube015.geometry} material={materials['black skin']} />
          <mesh geometry={nodes.Cube015_1.geometry} material={materials.outline} />
        </group>
        <group position={[-0.051, 0.078, 0]} rotation={[Math.PI, 0.328, 0]} scale={[-0.02, -0.02, -0.018]}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials['black plactic']} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials.outline} />
        </group>
        <group position={[-0.006, 0.078, -0.036]} rotation={[-Math.PI, 1.571, 0]} scale={[-0.02, -0.02, -0.018]}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials['black plactic']} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials.outline} />
        </group>
        <group position={[-0.04, 0.078, 0.054]} rotation={[Math.PI, -0.882, Math.PI]} scale={[0.02, 0.02, 0.018]}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials['black plactic']} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials.outline} />
        </group>
        <group position={[0.039, 0.078, -0.005]} rotation={[0, 0.389, 0]} scale={[0.02, 0.02, 0.018]}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials['black plactic']} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials.outline} />
        </group>
        <group position={[0.033, 0.079, 0.051]} rotation={[0, -0.712, 0]} scale={[0.02, 0.02, 0.018]}>
          <mesh geometry={nodes.Cube013_1.geometry} material={materials['black plactic']} />
          <mesh geometry={nodes.Cube013_2.geometry} material={materials.outline} />
        </group>
        <mesh geometry={nodes.Cube008.geometry} material={materials['black plactic']} position={[-0.005, 0.077, 0.016]} rotation={[0, -0.343, 0]} scale={[0.061, 0.034, 0.061]} />
        <mesh geometry={nodes.Cube009.geometry} material={materials['black plactic']} position={[-0.131, 0.291, 0.074]} rotation={[Math.PI, -0.452, Math.PI]} scale={[0.36, 0.412, 0.36]} />
        <mesh geometry={nodes.Cube020.geometry} material={materials['black skin']} position={[-0.008, 0.571, -0.129]} rotation={[-0.208, 0, 0]} scale={[0.119, 0.115, 0.093]} />
        <group position={[0.168, 0.359, -0.064]} rotation={[-0.12, 0.051, -0.401]} scale={0.255}>
          <mesh geometry={nodes.Cube014.geometry} material={materials['black skin']} />
          <mesh geometry={nodes.Cube014_1.geometry} material={materials.outline} />
        </group>
        <mesh geometry={nodes.Cylinder.geometry} material={materials['black plactic']} position={[-0.004, 0.141, 0.015]} scale={0.028} />
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['black plactic']} position={[-0.006, 0.016, -0.276]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-0.283} />
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['black plactic']} position={[-0.275, 0.016, -0.077]} rotation={[Math.PI / 2, 0, 0.315]} scale={0.283} />
        <group position={[0.245, 0.34, 0.148]} scale={[0.012, 0.006, 0.017]}>
          <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['black skin']} />
          <mesh geometry={nodes.Cylinder006_2.geometry} material={materials['metal.001']} />
        </group>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['black plactic']} position={[0.265, 0.016, -0.098]} rotation={[-Math.PI / 2, 0, 0.435]} scale={-0.283} />
        <mesh geometry={nodes.Cylinder008.geometry} material={materials['black plactic']} position={[0.214, 0.018, 0.206]} rotation={[-Math.PI / 2, 0, -0.73]} scale={-0.283} />
        <mesh geometry={nodes.Cylinder009.geometry} material={materials['black plactic']} position={[-0.191, 0.016, 0.238]} rotation={[Math.PI / 2, 0, -0.876]} scale={0.283} />
        <mesh geometry={nodes.Object.geometry} material={materials['black plactic']} position={[-0.004, 0.275, 0.178]} rotation={[3.129, 0, Math.PI]} scale={[1.063, 0.907, 1.004]} />
        <mesh geometry={nodes.Object001.geometry} material={materials['black plactic']} position={[-0.004, 0.313, 0.117]} rotation={[Math.PI, 0, Math.PI]} scale={[1.637, 1.063, 1.063]} />
        <mesh geometry={nodes.Plane001.geometry} material={materials['black skin']} position={[-0.005, 0.885, -0.24]} rotation={[1.502, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[-0.19, 0.525, -0.13]} rotation={[-0.126, 0.075, -1.481]} scale={0.013} />
        <mesh geometry={nodes.Plane005.geometry} material={materials['Material.001']} position={[0.187, 0.356, -0.113]} rotation={[-0.119, 0.179, -1.549]} scale={0.013} />
        <mesh geometry={nodes.Plane006.geometry} material={materials['Material.001']} position={[0.187, 0.356, -0.113]} rotation={[-0.119, 0.179, -1.549]} scale={0.013} />
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.001']} position={[0.196, 0.356, -0.114]} rotation={[-0.119, 0.179, -1.549]} scale={0.013} />
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.001']} position={[0.196, 0.356, -0.114]} rotation={[-0.119, 0.179, -1.549]} scale={0.013} />
        <mesh geometry={nodes.Plane010.geometry} material={materials.outline} position={[0.07, 0.585, -0.074]} rotation={[1.293, 0, 0]} scale={[0.019, 0.079, 0.079]} />
        <mesh geometry={nodes.Plane011.geometry} material={materials['Material.001']} position={[0.191, 0.356, -0.113]} rotation={[-0.123, 0.177, -1.528]} scale={0.013} />
        <mesh geometry={nodes.Plane013.geometry} material={materials.outline} position={[-0.005, 0.883, -0.189]} rotation={[1.381, 0, 0]} scale={[0.118, 0.087, 0.08]} />
        <group position={[0.245, 0.584, 0.166]} scale={[0.169, 0.255, 0.266]}>
          <mesh geometry={nodes.Plane006_1.geometry} material={materials['black skin']} />
          <mesh geometry={nodes.Plane006_2.geometry} material={materials.outline} />
        </group>
        <mesh geometry={nodes.Plane022.geometry} material={materials['Material.002']} position={[-0.005, 0.883, -0.189]} rotation={[1.381, 0, 0]} scale={[0.118, 0.087, 0.079]} />
        <mesh geometry={nodes.Plane023.geometry} material={materials['black skin']} position={[0.06, 0.922, -0.221]} rotation={[1.525, 0, 0]} scale={[0.038, 0.034, 0.038]} />
        <group position={[-0.006, 0.774, -0.178]} rotation={[1.605, 0, 0]} scale={[0.132, 0.143, 0.096]}>
          <mesh geometry={nodes.Plane012.geometry} material={materials['black skin']} />
          <mesh geometry={nodes.Plane012_1.geometry} material={materials.outline} />
        </group>
        <mesh geometry={nodes.Text.geometry} material={materials.outline} position={[-0.051, 1.041, -0.205]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
      </group>
      <group position={[-1.995, 0, 2.738]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.715}>
        <mesh geometry={nodes.ground001.geometry} material={materials['TT_checker_1024x1024_UV_GRID.001']} />
        <mesh geometry={nodes.plant001.geometry} material={materials.leave_1_MatSG} />
        <mesh geometry={nodes.pot001.geometry} material={materials['TT_checker_1024x1024_UV_GRID.001']} />
      </group>
      <group position={[-1.12, 0.018, -1.962]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.226}>
        <mesh geometry={nodes.book_cover_1.geometry} material={materials['book cover']} position={[-0.13, 0.236, -0.336]} />
        <mesh geometry={nodes.book_cover_2.geometry} material={materials['book cover 2']} position={[-0.13, 0.262, -0.336]} rotation={[0, -0.105, 0]} />
        <mesh geometry={nodes.book_pages_1.geometry} material={nodes.book_pages_1.material} position={[-0.13, 0.236, -0.336]} />
        <mesh geometry={nodes.book_pages_2.geometry} material={nodes.book_pages_2.material} position={[-0.13, 0.262, -0.336]} rotation={[0, -0.105, 0]} />
        <mesh geometry={nodes.table_leg.geometry} material={materials['wood.001']} position={[0, 0.309, 0]} />
        <mesh geometry={nodes.table_top.geometry} material={materials['wood.001']} position={[0, 0.309, 0]} />
      </group>
      <group position={[-1.063, 0.516, -1.961]} rotation={[0, Math.PI / 2, 0]} scale={1.832}>
        <group position={[0.011, 0.018, 0.011]}>
          <mesh geometry={nodes.Plane017.geometry} material={materials['Cover book-02']} />
          <mesh geometry={nodes.Plane017_1.geometry} material={materials.paper} />
        </group>
        <group position={[-0.071, 0.052, -0.01]}>
          <mesh geometry={nodes.garfo_decorativo.geometry} material={materials['black metal capo']} />
          <mesh geometry={nodes.garfo_decorativo_1.geometry} material={materials['white plastic capo']} />
        </group>
        <group position={[-0.072, 0.052, -0.027]}>
          <mesh geometry={nodes.decorative_knife_1.geometry} material={materials['black metal capo']} />
          <mesh geometry={nodes.decorative_knife_2.geometry} material={materials['white plastic capo']} />
        </group>
        <group position={[-0.06, 0.052, -0.006]}>
          <mesh geometry={nodes.decorative_knife001_1.geometry} material={materials['black metal capo']} />
          <mesh geometry={nodes.decorative_knife001_2.geometry} material={materials['white plastic capo']} />
        </group>
        <mesh geometry={nodes.Glass.geometry} material={materials.Glass} position={[-0.069, 0.05, -0.012]} />
        <group position={[0.065, 0.05, 0.054]}>
          <mesh geometry={nodes.snail_1.geometry} material={materials['black plastic watch']} />
          <mesh geometry={nodes.snail_2.geometry} material={materials['metal watch']} />
          <mesh geometry={nodes.snail_3.geometry} material={materials['light wood watch']} />
          <mesh geometry={nodes.snail_4.geometry} material={materials['brown wood watch']} />
          <mesh geometry={nodes.snail_5.geometry} material={materials['Brown lacquered wood watch']} />
        </group>
        <group position={[0.184, 0, 0.062]}>
          <mesh geometry={nodes.vase_1.geometry} material={materials.plant} />
          <mesh geometry={nodes.vase_2.geometry} material={materials.ground} />
          <mesh geometry={nodes.vase_3.geometry} material={materials['concrete vase']} />
        </group>
        <mesh geometry={nodes.Plane016.geometry} material={materials['Cover book-03']} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.paper} />
      </group>
      <group position={[-0.542, 0, 0]} scale={1.182}>
        <group position={[2.922, 0, 0.642]} rotation={[0, -Math.PI / 2, 0]} scale={1.323}>
          <mesh geometry={nodes.Cube021_1.geometry} material={materials.stand_stainless} />
          <mesh geometry={nodes.Cube021_2.geometry} material={materials.stand_connector} />
          <mesh geometry={nodes.Cube021_3.geometry} material={materials.stand_handle} />
        </group>
      </group>
      <group position={[2.91, 1.147, 0.755]} rotation={[0, -Math.PI / 2, 0]} scale={1.223}>
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['ham_buttons 1.002']} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials['ham_buttons 2.002']} />
        <mesh geometry={nodes.Cube023_3.geometry} material={materials['ham_buttons 3.002']} />
        <mesh geometry={nodes.Cube023_4.geometry} material={materials['ham_buttons 4.002']} />
        <mesh geometry={nodes.Cube023_5.geometry} material={materials['ham_main color.002']} />
        <mesh geometry={nodes.Cube023_6.geometry} material={materials['ham_speaker screen.002']} />
        <mesh geometry={nodes.Cube023_7.geometry} material={materials['ham_white keys.002']} />
        <mesh geometry={nodes.Cube023_8.geometry} material={materials['ham_black keys.002']} />
        <mesh geometry={nodes.Cube023_9.geometry} material={materials['ham_buttons metal 1.002']} />
        <mesh geometry={nodes.Cube023_10.geometry} material={materials['ham_buttons metal 2.002']} />
        <mesh geometry={nodes.Cube023_11.geometry} material={materials['ham_screen digital.002']} />
      </group>
      <group position={[2.265, 3.256, 3.398]} rotation={[Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.mount_01.geometry} material={materials.ring_paint} position={[-0.001, 0.015, 0.329]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Bolt001.geometry} material={materials['metals (aluminium)']} position={[0.023, 0.02, 0.001]} rotation={[Math.PI / 2, 0, 0]} />
        </mesh>
        <mesh geometry={nodes.mount_02.geometry} material={materials.ring_paint} position={[-0.002, 0.26, 0.218]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Weld_4.geometry} material={materials.ring_paint} position={[15.429, 6.302, 9.966]} scale={0.2} />
        </mesh>
        <group position={[-0.003, 0.261, 0.218]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.net_1.geometry} material={materials['plasticRed.001']} />
          <mesh geometry={nodes.net_2.geometry} material={materials.hoop_string} />
        </group>
        <mesh geometry={nodes.ring.geometry} material={materials.ring_paint} position={[-0.002, 0.26, 0.218]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.shield.geometry} material={materials.hoop_wall} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[1.695, 0, 3.008]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.433}>
        <mesh geometry={nodes.DOWN.geometry} material={materials['Material.017']} scale={0.104} />
        <mesh geometry={nodes.NET.geometry} material={materials['Material.017']} scale={0.106} />
        <mesh geometry={nodes.UP.geometry} material={materials['Material.017']} scale={0.104} />
      </group>
      <directionalLight intensity={2732} decay={2} position={[13.238, 11.31, -13.585]} rotation={[-2.552, 0.527, -3.071]} />
      <group position={[0, 0, -0.106]} scale={3.504}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Bricks} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.Default} />
      </group>
      <mesh geometry={nodes.Window1.geometry} material={nodes.Window1.material} position={[3.416, 2.38, 1.728]} scale={[0.493, 0.69, 1.203]} />
      <mesh geometry={nodes.Window2.geometry} material={nodes.Window2.material} position={[3.416, 2.38, -1.272]} scale={[0.493, 0.69, 1.203]} />
      <group position={[0, 0, 2.544]} rotation={[Math.PI, 0, Math.PI]} scale={[2.226, 1.681, 1.681]}>
        <mesh geometry={nodes.Kostka002.geometry} material={materials['Desk wood']} />
        <mesh geometry={nodes.Kostka002_1.geometry} material={materials['Metal Black Dixon']} />
      </group>
      <group position={[-1.144, 0, -1.744]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes['37685'].geometry} material={materials['Lassen Handwoven Rug']} />
        <mesh geometry={nodes['37685_1'].geometry} material={materials.occlusion} />
        <mesh geometry={nodes['37685_2'].geometry} material={materials.QR345346} />
      </group>
      <mesh geometry={nodes.Gamer_neon_rgb_light.geometry} material={materials['매테리얼.011']} position={[-2.258, 2.878, 3.315]} rotation={[-Math.PI / 2, -1.57, 0]} scale={4.912} />
      <group position={[-0.988, 1.21, 2.948]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.809}>
        <mesh geometry={nodes.Cylinder015.geometry} material={materials.Base_basketball} />
        <mesh geometry={nodes.Cylinder015_1.geometry} material={materials.LeBron_Material} />
      </group>
      <group position={[3.189, 2.547, -3.097]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Plane019.geometry} material={materials['background painting']} />
        <mesh geometry={nodes.Plane019_1.geometry} material={materials['Metal ']} />
      </group>
      <mesh geometry={nodes.basketball.geometry} material={materials.Basketball} position={[2.592, 0, 2.592]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.217} />
      <mesh geometry={nodes.di.geometry} material={materials['材质.005']} position={[0.909, 1.21, 3.01]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.643} />
    </group>
  )
}

useGLTF.preload('/Room.glb')
